# Chapter 4: Data Transformation Techniques

## Simple aggregations

### How to do it...

In [1]:
import polars as pl

In [2]:
df = pl.read_csv('../data/contoso_sales.csv', try_parse_dates=True)

In [3]:
df.head()

shape: (5, 20)
┌────────┬────────┬─────────────┬─────────────┬───┬─────────────┬───────┬─────────────┬────────────┐
│ Order  ┆ Line   ┆ Order Date  ┆ Delivery    ┆ … ┆ Net Price   ┆ Unit  ┆ Currency    ┆ Exchange   │
│ Number ┆ Number ┆ ---         ┆ Date        ┆   ┆ ---         ┆ Cost  ┆ Code        ┆ Rate       │
│ ---    ┆ ---    ┆ date        ┆ ---         ┆   ┆ f64         ┆ ---   ┆ ---         ┆ ---        │
│ i64    ┆ i64    ┆             ┆ date        ┆   ┆             ┆ f64   ┆ str         ┆ f64        │
╞════════╪════════╪═════════════╪═════════════╪═══╪═════════════╪═══════╪═════════════╪════════════╡
│ 284806 ┆ 1      ┆ 2017-10-18  ┆ 2017-10-20  ┆ … ┆ 10.288      ┆ 5.958 ┆ USD         ┆ 1.0        │
│ 285506 ┆ 1      ┆ 2017-10-25  ┆ 2017-10-26  ┆ … ┆ 11.691      ┆ 5.958 ┆ AUD         ┆ 1.2967     │
│ 311002 ┆ 2      ┆ 2018-07-07  ┆ 2018-07-12  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.3484     │
│ 366307 ┆ 2      ┆ 2020-01-11  ┆ 2020-01-11  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.4545     │
│ 325708 ┆ 3      ┆ 2018-12-01  ┆ 2018-12-02  ┆ … ┆ 11.5611     ┆ 6.62  ┆ USD         ┆ 1.0        │
└────────┴────────┴─────────────┴─────────────┴───┴─────────────┴───────┴─────────────┴────────────┘

In [5]:
df['Color'].unique()

shape: (17,)
Series: 'Color' [str]
[
	"Yellow"
	"Gold"
	"Purple"
	"Pink"
	"Grey"
	…
	"Green"
	"Black"
	"Silver"
	"Orange"
	"White"
]

In [7]:
import polars.selectors as cs

(
    df
    .select(cs.numeric())
    .sum()
)

shape: (1, 8)
┌─────────────┬────────┬─────────────┬──────────┬─────────────┬───────────┬───────────┬────────────┐
│ Order       ┆ Line   ┆ Customer    ┆ Quantity ┆ Unit Price  ┆ Net Price ┆ Unit Cost ┆ Exchange   │
│ Number      ┆ Number ┆ Age         ┆ ---      ┆ ---         ┆ ---       ┆ ---       ┆ Rate       │
│ ---         ┆ ---    ┆ ---         ┆ i64      ┆ f64         ┆ f64       ┆ f64       ┆ ---        │
│ i64         ┆ i64    ┆ i64         ┆          ┆             ┆           ┆           ┆ f64        │
╞═════════════╪════════╪═════════════╪══════════╪═════════════╪═══════════╪═══════════╪════════════╡
│ 4466019052  ┆ 16195  ┆ 725757      ┆ 43517    ┆ 4.1785e6    ┆ 3.9286e6  ┆ 1.7356e6  ┆ 14124.4597 │
└─────────────┴────────┴─────────────┴──────────┴─────────────┴───────────┴───────────┴────────────┘

In [8]:
s = df.select('Quantity').to_series()
s.sum()

43517

In [11]:
df.select(pl.col('Quantity').sum())

shape: (1, 1)
┌──────────┐
│ Quantity │
│ ---      │
│ i64      │
╞══════════╡
│ 43517    │
└──────────┘

In [12]:
df.select(
    pl.col('Customer Name').first().alias('Cust Name First'),
    pl.col('Customer Name').last().alias('Cust Name Last')
)

shape: (1, 2)
┌─────────────────┬────────────────┐
│ Cust Name First ┆ Cust Name Last │
│ ---             ┆ ---            │
│ str             ┆ str            │
╞═════════════════╪════════════════╡
│ Eric Kennedy    ┆ Billy Ratliff  │
└─────────────────┴────────────────┘

In [17]:
df.select(
    pl.col('Customer Name').str.split(' ').list.first().alias('First Name'),
    pl.col('Customer Name').str.split(' ').list.last().alias('Last Name')
)

shape: (13_915, 2)
┌────────────┬───────────┐
│ First Name ┆ Last Name │
│ ---        ┆ ---       │
│ str        ┆ str       │
╞════════════╪═══════════╡
│ Eric       ┆ Kennedy   │
│ George     ┆ Tooth     │
│ Caleb      ┆ Greene    │
│ Isaac      ┆ Siddins   │
│ Mike       ┆ McQueen   │
│ …          ┆ …         │
│ Xavier     ┆ Clay      │
│ Ginger     ┆ Paine     │
│ Finlay     ┆ Pugh      │
│ Joseph     ┆ Reyes     │
│ Billy      ┆ Ratliff   │
└────────────┴───────────┘

In [18]:
df.select(cs.numeric()).describe()

shape: (9, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ Order     ┆ Line      ┆ Customer  ┆ … ┆ Unit      ┆ Net Price ┆ Unit Cost ┆ Exchange │
│ ---       ┆ Number    ┆ Number    ┆ Age       ┆   ┆ Price     ┆ ---       ┆ ---       ┆ Rate     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 13915.0   ┆ 13915.0   ┆ 13915.0   ┆ … ┆ 13915.0   ┆ 13915.0   ┆ 13915.0   ┆ 13915.0  │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 320949.98 ┆ 1.163852  ┆ 52.15645  ┆ … ┆ 300.28425 ┆ 282.32739 ┆ 124.73136 ┆ 1.015053 │
│           ┆ 5771      ┆           ┆           ┆   ┆           ┆           ┆ 4         ┆          │
│ std       ┆ 28431.791 ┆ 1.361349  ┆ 19.133881 ┆ … ┆ 405.53897 ┆ 381.73884 ┆ 147.94409 ┆ 0.171927 │
│           ┆ 36        ┆           ┆           ┆   ┆ 5         ┆ 7         ┆ 4         ┆          │
│ min       ┆ 269500.0  ┆ 0.0       ┆ 19.0      ┆ … ┆ 0.95      ┆ 0.8265    ┆ 0.48      ┆ 0.7015   │
│ 25%       ┆ 295902.0  ┆ 0.0       ┆ 36.0      ┆ … ┆ 46.99     ┆ 43.4      ┆ 21.92     ┆ 0.8965   │
│ 50%       ┆ 319806.0  ┆ 1.0       ┆ 52.0      ┆ … ┆ 207.987   ┆ 194.91    ┆ 86.68     ┆ 1.0      │
│ 75%       ┆ 345106.0  ┆ 2.0       ┆ 68.0      ┆ … ┆ 361.2     ┆ 336.0     ┆ 160.93    ┆ 1.0      │
│ max       ┆ 371503.0  ┆ 6.0       ┆ 85.0      ┆ … ┆ 3748.5    ┆ 3748.5    ┆ 1241.955  ┆ 1.5373   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### There is more...

In [19]:
df.select(
    (pl.col('Quantity') >= 4).sum()
)

shape: (1, 1)
┌──────────┐
│ Quantity │
│ ---      │
│ u32      │
╞══════════╡
│ 4423     │
└──────────┘

In [26]:
df.select(
    pl.col('Quantity').filter(pl.col('Store Name')=='Online store').sum()
)

shape: (1, 1)
┌──────────┐
│ Quantity │
│ ---      │
│ i64      │
╞══════════╡
│ 25017    │
└──────────┘

## Using group by aggregations

### How to do it...

In [1]:
import polars as pl

In [2]:
df = pl.read_csv('../data/contoso_sales.csv', try_parse_dates=True)
df.head()

In [27]:
df.group_by('Brand')

In [28]:
(
    df
    .group_by('Brand')
    .agg(pl.col('Quantity').sum().alias('Sum of Quantity'))
    .head()
)

shape: (5, 2)
┌───────────────────┬─────────────────┐
│ Brand             ┆ Sum of Quantity │
│ ---               ┆ ---             │
│ str               ┆ i64             │
╞═══════════════════╪═════════════════╡
│ A. Datum          ┆ 555             │
│ Northwind Traders ┆ 638             │
│ Southridge Video  ┆ 6749            │
│ Fabrikam          ┆ 1516            │
│ Contoso           ┆ 11132           │
└───────────────────┴─────────────────┘

In [29]:
(
    df
    .group_by('Brand')
    .agg(
        pl.col('Quantity').sum().alias('Sum of Quantity'),
        pl.col('Unit Price').mean().alias('Average Unit Price'),
    )
    .sort('Average Unit Price', descending=True)
    .head()
)

shape: (5, 3)
┌─────────────────┬─────────────────┬────────────────────┐
│ Brand           ┆ Sum of Quantity ┆ Average Unit Price │
│ ---             ┆ ---             ┆ ---                │
│ str             ┆ i64             ┆ f64                │
╞═════════════════╪═════════════════╪════════════════════╡
│ Fabrikam        ┆ 332             ┆ 795.820192         │
│ Contoso         ┆ 977             ┆ 715.378268         │
│ Adventure Works ┆ 4616            ┆ 620.330242         │
│ Litware         ┆ 161             ┆ 603.528818         │
│ Fabrikam        ┆ 1516            ┆ 557.956117         │
└─────────────────┴─────────────────┴────────────────────┘

In [31]:
ctx = pl.SQLContext(df=df)

In [35]:
ctx.execute(
    """SELECT Brand,
              SUM(Quantity) AS "Sum of Quantity",
              AVG("Unit Price") AS "Average Unit Price"
       FROM df
       GROUP BY Brand
       ORDER BY "Average Unit Price" DESC
       LIMIT 5
    """
).collect()

shape: (5, 3)
┌─────────────────┬─────────────────┬────────────────────┐
│ Brand           ┆ Sum of Quantity ┆ Average Unit Price │
│ ---             ┆ ---             ┆ ---                │
│ str             ┆ i64             ┆ f64                │
╞═════════════════╪═════════════════╪════════════════════╡
│ Fabrikam        ┆ 332             ┆ 795.820192         │
│ Contoso         ┆ 977             ┆ 715.378268         │
│ Adventure Works ┆ 4616            ┆ 620.330242         │
│ Litware         ┆ 161             ┆ 603.528818         │
│ Fabrikam        ┆ 1516            ┆ 557.956117         │
└─────────────────┴─────────────────┴────────────────────┘

In [40]:
(
    df
    .group_by('Brand')
    .agg(
        pl.col('Unit Price').mean().round(2).alias('Average Unit Price'),
        (pl.col('Unit Price').sum() / pl.len()).round(2).alias('Average Unit Price 2'),
        pl.col('Customer Name').first(),
        pl.col('Category').last()
    )
    .sort(['Brand', 'Average Unit Price'], descending=[False, True])
    .head()
)

shape: (5, 5)
┌──────────────────┬──────────────┬──────────────────────┬──────────────────┬─────────────────┐
│ Brand            ┆ Average Unit ┆ Average Unit Price 2 ┆ Customer Name    ┆ Category        │
│ ---              ┆ Price        ┆ ---                  ┆ ---              ┆ ---             │
│ str              ┆ ---          ┆ f64                  ┆ str              ┆ str             │
│                  ┆ f64          ┆                      ┆                  ┆                 │
╞══════════════════╪══════════════╪══════════════════════╪══════════════════╪═════════════════╡
│ A. Datum         ┆ 280.1        ┆ 280.1                ┆ Blažena Salabová ┆ Cameras and     │
│                  ┆              ┆                      ┆                  ┆ camcorders      │
│ Adventure Works  ┆ 620.33       ┆ 620.33               ┆ Molly Walters    ┆ Home Appliances │
│ Adventure Works  ┆ 166.9        ┆ 166.9                ┆ James Steinfeld  ┆ TV and Video    │
│ Contoso          ┆ 150.86       ┆ 150.86               ┆ Eric Kennedy     ┆ Cell phones     │
│ Contoso          ┆ 715.38       ┆ 715.38               ┆ Chiquita Boyd    ┆ Home Appliances │
└──────────────────┴──────────────┴──────────────────────┴──────────────────┴─────────────────┘

In [36]:
(
    df
    .group_by('Brand')
    .agg(
        pl.col('Unit Price').mean().round(2).alias('Average Unit Price'),
        (pl.col('Unit Price').sum() / pl.len()).round(2).alias('Average Unit Price 2'),
        pl.col('Customer Name').first(),
        pl.col('Category').last()
    )
    .sort('Average Unit Price', descending=True)
    .sort('Brand')
    .head()
)

shape: (5, 5)
┌──────────────────┬──────────────┬──────────────────────┬──────────────────┬─────────────────┐
│ Brand            ┆ Average Unit ┆ Average Unit Price 2 ┆ Customer Name    ┆ Category        │
│ ---              ┆ Price        ┆ ---                  ┆ ---              ┆ ---             │
│ str              ┆ ---          ┆ f64                  ┆ str              ┆ str             │
│                  ┆ f64          ┆                      ┆                  ┆                 │
╞══════════════════╪══════════════╪══════════════════════╪══════════════════╪═════════════════╡
│ A. Datum         ┆ 280.1        ┆ 280.1                ┆ Blažena Salabová ┆ Cameras and     │
│                  ┆              ┆                      ┆                  ┆ camcorders      │
│ Adventure Works  ┆ 620.33       ┆ 620.33               ┆ Molly Walters    ┆ Home Appliances │
│ Adventure Works  ┆ 166.9        ┆ 166.9                ┆ James Steinfeld  ┆ TV and Video    │
│ Contoso          ┆ 150.86       ┆ 150.86               ┆ Eric Kennedy     ┆ Cell phones     │
│ Contoso          ┆ 715.38       ┆ 715.38               ┆ Chiquita Boyd    ┆ Home Appliances │
└──────────────────┴──────────────┴──────────────────────┴──────────────────┴─────────────────┘

In [43]:
ctx.execute(
    """
        SELECT Brand,
               ROUND(AVG("Unit Price"), 2) AS "Average Unit Price",
               ROUND(SUM("Unit Price") / COUNT("Unit Price"), 2) AS "Average Unit Price 2",
               FIRST("Customer Name"),
               LAST("Category")
        FROM df
        GROUP BY Brand
        ORDER BY Brand, "Average Unit Price" DESC
        LIMIT 5
    """
).collect()

shape: (5, 5)
┌──────────────────┬──────────────┬──────────────────────┬──────────────────┬─────────────────┐
│ Brand            ┆ Average Unit ┆ Average Unit Price 2 ┆ Customer Name    ┆ Category        │
│ ---              ┆ Price        ┆ ---                  ┆ ---              ┆ ---             │
│ str              ┆ ---          ┆ f64                  ┆ str              ┆ str             │
│                  ┆ f64          ┆                      ┆                  ┆                 │
╞══════════════════╪══════════════╪══════════════════════╪══════════════════╪═════════════════╡
│ A. Datum         ┆ 280.1        ┆ 280.1                ┆ Blažena Salabová ┆ Cameras and     │
│                  ┆              ┆                      ┆                  ┆ camcorders      │
│ Adventure Works  ┆ 620.33       ┆ 620.33               ┆ Molly Walters    ┆ Home Appliances │
│ Adventure Works  ┆ 166.9        ┆ 166.9                ┆ James Steinfeld  ┆ TV and Video    │
│ Contoso          ┆ 150.86       ┆ 150.86               ┆ Eric Kennedy     ┆ Cell phones     │
│ Contoso          ┆ 715.38       ┆ 715.38               ┆ Chiquita Boyd    ┆ Home Appliances │
└──────────────────┴──────────────┴──────────────────────┴──────────────────┴─────────────────┘

In [44]:
(
    pl.scan_csv('../data/contoso_sales.csv', try_parse_dates=True)
    .group_by('Brand')
    .agg(
        pl.col('Unit Price').mean().round(2).alias('Average Unit Price'),
        (pl.col('Unit Price').sum() / pl.len()).round(2).alias('Average Unit Price 2'),
        pl.col('Customer Name').first(),
        pl.col('Category').last()
    )
    .sort('Average Unit Price', descending=True)
    .sort('Brand')
    .collect()
    .head()
)

shape: (5, 5)
┌──────────────────┬──────────────┬──────────────────────┬──────────────────┬─────────────────┐
│ Brand            ┆ Average Unit ┆ Average Unit Price 2 ┆ Customer Name    ┆ Category        │
│ ---              ┆ Price        ┆ ---                  ┆ ---              ┆ ---             │
│ str              ┆ ---          ┆ f64                  ┆ str              ┆ str             │
│                  ┆ f64          ┆                      ┆                  ┆                 │
╞══════════════════╪══════════════╪══════════════════════╪══════════════════╪═════════════════╡
│ A. Datum         ┆ 280.1        ┆ 280.1                ┆ Blažena Salabová ┆ Cameras and     │
│                  ┆              ┆                      ┆                  ┆ camcorders      │
│ Adventure Works  ┆ 620.33       ┆ 620.33               ┆ Molly Walters    ┆ Home Appliances │
│ Adventure Works  ┆ 166.9        ┆ 166.9                ┆ James Steinfeld  ┆ TV and Video    │
│ Contoso          ┆ 150.86       ┆ 150.86               ┆ Eric Kennedy     ┆ Cell phones     │
│ Contoso          ┆ 715.38       ┆ 715.38               ┆ Chiquita Boyd    ┆ Home Appliances │
└──────────────────┴──────────────┴──────────────────────┴──────────────────┴─────────────────┘

In [51]:
pl.Config.set_fmt_str_lengths = 5
print(df.select('Brand').unique().head(10))

shape: (10, 1)
┌───────────────────┐
│ Brand             │
│ ---               │
│ str               │
╞═══════════════════╡
│ Adventure Works   │
│ Southridge Video  │
│ Northwind Traders │
│ Litware           │
│ Contoso           │
│ Contoso           │
│ Adventure Works   │
│ Proseware         │
│ Litware           │
│ Fabrikam          │
└───────────────────┘

In [54]:
df.select('Brand').unique().head(10)

shape: (10, 1)
┌──────────────────────┐
│ Brand                │
│ ---                  │
│ str                  │
╞══════════════════════╡
│ Litware              │
│ A. Datum             │
│ Tailspin Toys        │
│ Proseware            │
│ Northwind Traders    │
│ Fabrikam             │
│ Contoso              │
│ Wide World Importers │
│ Litware              │
│ Contoso              │
└──────────────────────┘

In [55]:
import os
os.environ['POLARS_FMT_STR_LEN'] = str(50)

df.select('Brand').unique().head(10)

shape: (10, 1)
┌──────────────────────┐
│ Brand                │
│ ---                  │
│ str                  │
╞══════════════════════╡
│ Litware              │
│ Adventure Works      │
│ Adventure Works      │
│ Wide World Importers │
│ Proseware            │
│ Northwind Traders    │
│ Tailspin Toys        │
│ Fabrikam             │
│ Southridge Video     │
│ Fabrikam             │
└──────────────────────┘

### There is more...

In [56]:
for name, data in df.group_by(['Brand']):
    print(name[0], type(data))

Tailspin Toys <class 'polars.dataframe.frame.DataFrame'>
Litware  <class 'polars.dataframe.frame.DataFrame'>
Proseware <class 'polars.dataframe.frame.DataFrame'>
Wide World Importers <class 'polars.dataframe.frame.DataFrame'>
The Phone Company <class 'polars.dataframe.frame.DataFrame'>
Contoso  <class 'polars.dataframe.frame.DataFrame'>
Northwind Traders <class 'polars.dataframe.frame.DataFrame'>
Adventure Works <class 'polars.dataframe.frame.DataFrame'>
Fabrikam   <class 'polars.dataframe.frame.DataFrame'>
Adventure Works  <class 'polars.dataframe.frame.DataFrame'>
Southridge Video <class 'polars.dataframe.frame.DataFrame'>
Contoso <class 'polars.dataframe.frame.DataFrame'>
Litware <class 'polars.dataframe.frame.DataFrame'>
A. Datum <class 'polars.dataframe.frame.DataFrame'>
Fabrikam <class 'polars.dataframe.frame.DataFrame'>

In [62]:
(
    df
    .group_by('Brand')
    .agg(pl.col('Quantity'))
    .head()
)

shape: (5, 2)
┌───────────────────┬─────────────┐
│ Brand             ┆ Quantity    │
│ ---               ┆ ---         │
│ str               ┆ list[i64]   │
╞═══════════════════╪═════════════╡
│ Contoso           ┆ [3, 1, … 3] │
│ A. Datum          ┆ [2, 1, … 2] │
│ The Phone Company ┆ [3, 5, … 4] │
│ Fabrikam          ┆ [2, 1, … 2] │
│ Adventure Works   ┆ [5, 7, … 2] │
└───────────────────┴─────────────┘

In [63]:
(
    df
    .group_by('Brand', maintain_order=True)
    .agg(pl.col('Quantity'))
    .head()
)

shape: (5, 2)
┌──────────────────────┬─────────────┐
│ Brand                ┆ Quantity    │
│ ---                  ┆ ---         │
│ str                  ┆ list[i64]   │
╞══════════════════════╪═════════════╡
│ Contoso              ┆ [7, 1, … 3] │
│ Wide World Importers ┆ [2, 8, … 2] │
│ Northwind Traders    ┆ [2, 3, … 2] │
│ Adventure Works      ┆ [2, 3, … 6] │
│ Adventure Works      ┆ [5, 7, … 2] │
└──────────────────────┴─────────────┘

In [64]:
(
    df
    .group_by(
        pl.col('Brand'), 
        'Customer Country',
        pl.col('Order Date').dt.year().alias('Order Year')
        )
    .agg(pl.col('Unit Price').mean())
    .head()
)

shape: (5, 4)
┌──────────────────────┬──────────────────┬────────────┬────────────┐
│ Brand                ┆ Customer Country ┆ Order Year ┆ Unit Price │
│ ---                  ┆ ---              ┆ ---        ┆ ---        │
│ str                  ┆ str              ┆ i32        ┆ f64        │
╞══════════════════════╪══════════════════╪════════════╪════════════╡
│ Proseware            ┆ Australia        ┆ 2020       ┆ 1299.0     │
│ The Phone Company    ┆ United States    ┆ 2019       ┆ 284.531157 │
│ Litware              ┆ Canada           ┆ 2020       ┆ 369.663333 │
│ Wide World Importers ┆ France           ┆ 2020       ┆ 194.2475   │
│ A. Datum             ┆ Canada           ┆ 2020       ┆ 243.45     │
└──────────────────────┴──────────────────┴────────────┴────────────┘

## Aggregating values across multiple columns

### How to do it...

In [6]:
import polars as pl

In [65]:
df = pl.read_csv('../data/pokemon.csv')
df.head()

shape: (5, 13)
┌─────┬───────────────────────┬────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 65      ┆ 45    ┆ 1          ┆ false     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 80      ┆ 60    ┆ 1          ┆ false     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 100     ┆ 80    ┆ 1          ┆ false     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 120     ┆ 80    ┆ 1          ┆ false     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 50      ┆ 65    ┆ 1          ┆ false     │
└─────┴───────────────────────┴────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [66]:
(
    df
    .select('HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed')
    .sum_horizontal().alias('Total 2')
    .head()
)

shape: (10,)
Series: 'Total 2' [i64]
[
	318
	405
	525
	625
	309
	405
	534
	634
	634
	314
]

In [67]:
(
    df
    .with_columns(
        pl.sum_horizontal('HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed').alias('Total 2')
    )
    .head()
)

shape: (5, 14)
┌─────┬───────────────────────┬────────┬────────┬───┬───────┬────────────┬───────────┬─────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Speed ┆ Generation ┆ Legendary ┆ Total 2 │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---     │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64   ┆ i64        ┆ bool      ┆ i64     │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═══════╪════════════╪═══════════╪═════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 45    ┆ 1          ┆ false     ┆ 318     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 60    ┆ 1          ┆ false     ┆ 405     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 525     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 625     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 65    ┆ 1          ┆ false     ┆ 309     │
└─────┴───────────────────────┴────────┴────────┴───┴───────┴────────────┴───────────┴─────────┘

In [68]:
(
    df
    .with_columns(
        pl.concat_list('HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed').list.sum().alias('Total 2')
    )
    .head()
)

shape: (5, 14)
┌─────┬───────────────────────┬────────┬────────┬───┬───────┬────────────┬───────────┬─────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Speed ┆ Generation ┆ Legendary ┆ Total 2 │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---     │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64   ┆ i64        ┆ bool      ┆ i64     │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═══════╪════════════╪═══════════╪═════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 45    ┆ 1          ┆ false     ┆ 318     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 60    ┆ 1          ┆ false     ┆ 405     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 525     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 625     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 65    ┆ 1          ┆ false     ┆ 309     │
└─────┴───────────────────────┴────────┴────────┴───┴───────┴────────────┴───────────┴─────────┘

In [70]:
(
    df.with_columns(
        pl.concat_arr('HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed').arr.sum().alias('Total 2')
    )
    .head()
)

shape: (5, 14)
┌─────┬───────────────────────┬────────┬────────┬───┬───────┬────────────┬───────────┬─────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Speed ┆ Generation ┆ Legendary ┆ Total 2 │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---     │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64   ┆ i64        ┆ bool      ┆ i64     │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═══════╪════════════╪═══════════╪═════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 45    ┆ 1          ┆ false     ┆ 318     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 60    ┆ 1          ┆ false     ┆ 405     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 525     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 625     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 65    ┆ 1          ┆ false     ┆ 309     │
└─────┴───────────────────────┴────────┴────────┴───┴───────┴────────────┴───────────┴─────────┘

In [71]:
cols = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
(
    df
    .with_columns(
        pl.reduce(
            function=lambda acc, col: acc + col, 
            exprs=pl.col(cols)
        )
        .alias('Total 2')
    )
    .head()
)

shape: (5, 14)
┌─────┬───────────────────────┬────────┬────────┬───┬───────┬────────────┬───────────┬─────────┐
│ #   ┆ Name                  ┆ Type 1 ┆ Type 2 ┆ … ┆ Speed ┆ Generation ┆ Legendary ┆ Total 2 │
│ --- ┆ ---                   ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---     │
│ i64 ┆ str                   ┆ str    ┆ str    ┆   ┆ i64   ┆ i64        ┆ bool      ┆ i64     │
╞═════╪═══════════════════════╪════════╪════════╪═══╪═══════╪════════════╪═══════════╪═════════╡
│ 1   ┆ Bulbasaur             ┆ Grass  ┆ Poison ┆ … ┆ 45    ┆ 1          ┆ false     ┆ 318     │
│ 2   ┆ Ivysaur               ┆ Grass  ┆ Poison ┆ … ┆ 60    ┆ 1          ┆ false     ┆ 405     │
│ 3   ┆ Venusaur              ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 525     │
│ 3   ┆ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 625     │
│ 4   ┆ Charmander            ┆ Fire   ┆ null   ┆ … ┆ 65    ┆ 1          ┆ false     ┆ 309     │
└─────┴───────────────────────┴────────┴────────┴───┴───────┴────────────┴───────────┴─────────┘

In [80]:
(
    df
    .with_columns(
        pl.fold(
            acc=pl.lit(1, dtype=pl.Int64), 
            function=lambda acc, col: acc * col, 
            exprs=pl.col(cols)
        )
        .alias('Product')
    )
    .head()
)

shape: (5, 14)
┌─────┬──────────────┬────────┬────────┬───┬───────┬────────────┬───────────┬───────────────┐
│ #   ┆ Name         ┆ Type 1 ┆ Type 2 ┆ … ┆ Speed ┆ Generation ┆ Legendary ┆ Product       │
│ --- ┆ ---          ┆ ---    ┆ ---    ┆   ┆ ---   ┆ ---        ┆ ---       ┆ ---           │
│ i64 ┆ str          ┆ str    ┆ str    ┆   ┆ i64   ┆ i64        ┆ bool      ┆ i64           │
╞═════╪══════════════╪════════╪════════╪═══╪═══════╪════════════╪═══════════╪═══════════════╡
│ 1   ┆ Bulbasaur    ┆ Grass  ┆ Poison ┆ … ┆ 45    ┆ 1          ┆ false     ┆ 20542055625   │
│ 2   ┆ Ivysaur      ┆ Grass  ┆ Poison ┆ … ┆ 60    ┆ 1          ┆ false     ┆ 89994240000   │
│ 3   ┆ Venusaur     ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 435584000000  │
│ 3   ┆ VenusaurMega ┆ Grass  ┆ Poison ┆ … ┆ 80    ┆ 1          ┆ false     ┆ 1152460800000 │
│     ┆ Venusaur     ┆        ┆        ┆   ┆       ┆            ┆           ┆               │
│ 4   ┆ Charmander   ┆ Fire   ┆ null   ┆ … ┆ 65    ┆ 1          ┆ false     ┆ 17004780000   │
└─────┴──────────────┴────────┴────────┴───┴───────┴────────────┴───────────┴───────────────┘

### There is more...

In [81]:
(
    df
    .filter(
        pl.fold(
            acc=pl.lit(True), 
            function=lambda acc, col: acc & col, 
            exprs=pl.col(cols) > 80
        )
    )
    .head()
)

shape: (4, 13)
┌─────┬──────────┬──────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name     ┆ Type 1   ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str      ┆ str      ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪══════════╪══════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 144 ┆ Articuno ┆ Ice      ┆ Flying ┆ … ┆ 125     ┆ 85    ┆ 1          ┆ true      │
│ 145 ┆ Zapdos   ┆ Electric ┆ Flying ┆ … ┆ 90      ┆ 100   ┆ 1          ┆ true      │
│ 146 ┆ Moltres  ┆ Fire     ┆ Flying ┆ … ┆ 85      ┆ 90    ┆ 1          ┆ true      │
│ 150 ┆ Mewtwo   ┆ Psychic  ┆ null   ┆ … ┆ 90      ┆ 130   ┆ 1          ┆ true      │
└─────┴──────────┴──────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [85]:
df.filter(
    pl.all_horizontal(pl.col(cols) > 80)
)

shape: (4, 13)
┌─────┬──────────┬──────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name     ┆ Type 1   ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str      ┆ str      ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪══════════╪══════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 144 ┆ Articuno ┆ Ice      ┆ Flying ┆ … ┆ 125     ┆ 85    ┆ 1          ┆ true      │
│ 145 ┆ Zapdos   ┆ Electric ┆ Flying ┆ … ┆ 90      ┆ 100   ┆ 1          ┆ true      │
│ 146 ┆ Moltres  ┆ Fire     ┆ Flying ┆ … ┆ 85      ┆ 90    ┆ 1          ┆ true      │
│ 150 ┆ Mewtwo   ┆ Psychic  ┆ null   ┆ … ┆ 90      ┆ 130   ┆ 1          ┆ true      │
└─────┴──────────┴──────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [86]:
(
    df
    .filter(
        pl.all_horizontal(pl.col(cols) > 80)
    )
    .head()
)

shape: (4, 13)
┌─────┬──────────┬──────────┬────────┬───┬─────────┬───────┬────────────┬───────────┐
│ #   ┆ Name     ┆ Type 1   ┆ Type 2 ┆ … ┆ Sp. Def ┆ Speed ┆ Generation ┆ Legendary │
│ --- ┆ ---      ┆ ---      ┆ ---    ┆   ┆ ---     ┆ ---   ┆ ---        ┆ ---       │
│ i64 ┆ str      ┆ str      ┆ str    ┆   ┆ i64     ┆ i64   ┆ i64        ┆ bool      │
╞═════╪══════════╪══════════╪════════╪═══╪═════════╪═══════╪════════════╪═══════════╡
│ 144 ┆ Articuno ┆ Ice      ┆ Flying ┆ … ┆ 125     ┆ 85    ┆ 1          ┆ true      │
│ 145 ┆ Zapdos   ┆ Electric ┆ Flying ┆ … ┆ 90      ┆ 100   ┆ 1          ┆ true      │
│ 146 ┆ Moltres  ┆ Fire     ┆ Flying ┆ … ┆ 85      ┆ 90    ┆ 1          ┆ true      │
│ 150 ┆ Mewtwo   ┆ Psychic  ┆ null   ┆ … ┆ 90      ┆ 130   ┆ 1          ┆ true      │
└─────┴──────────┴──────────┴────────┴───┴─────────┴───────┴────────────┴───────────┘

In [90]:
str_cols = ['Name', 'Type 1', 'Type 2']
str_combined = pl.fold(acc=pl.lit(''), function=lambda acc, col: acc + col, exprs=str_cols).alias('Str Combined')
str_cols.append(str_combined)
df.select(str_cols).head()

shape: (5, 4)
┌───────────────────────┬────────┬────────┬──────────────────────────────────┐
│ Name                  ┆ Type 1 ┆ Type 2 ┆ Str Combined                     │
│ ---                   ┆ ---    ┆ ---    ┆ ---                              │
│ str                   ┆ str    ┆ str    ┆ str                              │
╞═══════════════════════╪════════╪════════╪══════════════════════════════════╡
│ Bulbasaur             ┆ Grass  ┆ Poison ┆ BulbasaurGrassPoison             │
│ Ivysaur               ┆ Grass  ┆ Poison ┆ IvysaurGrassPoison               │
│ Venusaur              ┆ Grass  ┆ Poison ┆ VenusaurGrassPoison              │
│ VenusaurMega Venusaur ┆ Grass  ┆ Poison ┆ VenusaurMega VenusaurGrassPoison │
│ Charmander            ┆ Fire   ┆ null   ┆ null                             │
└───────────────────────┴────────┴────────┴──────────────────────────────────┘

In [93]:
str_cols = ['Name', 'Type 1', 'Type 2']
df.select(pl.concat_str(str_cols, separator=' ', ignore_nulls=True)).head()

shape: (5, 1)
┌────────────────────────────────────┐
│ Name                               │
│ ---                                │
│ str                                │
╞════════════════════════════════════╡
│ Bulbasaur Grass Poison             │
│ Ivysaur Grass Poison               │
│ Venusaur Grass Poison              │
│ VenusaurMega Venusaur Grass Poison │
│ Charmander Fire                    │
└────────────────────────────────────┘

## Computing over groups with window functions

### How to do it...

In [ ]:
import polars as pl

In [94]:
import os 
os.environ['POLARS_FMT_STR_LEN'] = str(50)

In [95]:
df = pl.read_csv('../data/contoso_sales.csv', try_parse_dates=True)
df = df.with_columns(
    (pl.col('Quantity') * pl.col('Net Price')).round(2).alias('Sales Amount')
)
df.head()

shape: (5, 21)
┌────────┬────────┬────────────┬─────────────────┬───┬───────┬──────────┬─────────────────┬────────┐
│ Order  ┆ Line   ┆ Order Date ┆ Delivery Date   ┆ … ┆ Unit  ┆ Currency ┆ Exchange Rate   ┆ Sales  │
│ Number ┆ Number ┆ ---        ┆ ---             ┆   ┆ Cost  ┆ Code     ┆ ---             ┆ Amount │
│ ---    ┆ ---    ┆ date       ┆ date            ┆   ┆ ---   ┆ ---      ┆ f64             ┆ ---    │
│ i64    ┆ i64    ┆            ┆                 ┆   ┆ f64   ┆ str      ┆                 ┆ f64    │
╞════════╪════════╪════════════╪═════════════════╪═══╪═══════╪══════════╪═════════════════╪════════╡
│ 284806 ┆ 1      ┆ 2017-10-18 ┆ 2017-10-20      ┆ … ┆ 5.958 ┆ USD      ┆ 1.0             ┆ 72.02  │
│ 285506 ┆ 1      ┆ 2017-10-25 ┆ 2017-10-26      ┆ … ┆ 5.958 ┆ AUD      ┆ 1.2967          ┆ 11.69  │
│ 311002 ┆ 2      ┆ 2018-07-07 ┆ 2018-07-12      ┆ … ┆ 6.62  ┆ AUD      ┆ 1.3484          ┆ 77.94  │
│ 366307 ┆ 2      ┆ 2020-01-11 ┆ 2020-01-11      ┆ … ┆ 6.62  ┆ AUD      ┆ 1.4545          ┆ 51.96  │
│ 325708 ┆ 3      ┆ 2018-12-01 ┆ 2018-12-02      ┆ … ┆ 6.62  ┆ USD      ┆ 1.0             ┆ 23.12  │
└────────┴────────┴────────────┴─────────────────┴───┴───────┴──────────┴─────────────────┴────────┘

In [96]:
sales_by_cat = df.select(
    'Category',
    'Subcategory',
    pl.col('Sales Amount').sum().over('Category').alias('Sales Amt per Cat')
)
sales_by_cat.head()

shape: (5, 3)
┌──────────┬─────────────┬───────────────────┐
│ Category ┆ Subcategory ┆ Sales Amt per Cat │
│ ---      ┆ ---         ┆ ---               │
│ str      ┆ str         ┆ f64               │
╞══════════╪═════════════╪═══════════════════╡
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
└──────────┴─────────────┴───────────────────┘

In [97]:
ctx = pl.SQLContext(df=df)

ctx.execute(
    """SELECT Category, Subcategory,
              SUM("Sales Amount") OVER (PARTITION BY Category) AS "Sales Amt per Cat"
       FROM df
       LIMIT 5
    """
).collect()

shape: (5, 3)
┌──────────┬─────────────┬───────────────────┐
│ Category ┆ Subcategory ┆ Sales Amt per Cat │
│ ---      ┆ ---         ┆ ---               │
│ str      ┆ str         ┆ f64               │
╞══════════╪═════════════╪═══════════════════╡
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
└──────────┴─────────────┴───────────────────┘

In [98]:
pl.sql(
    """SELECT Category, Subcategory,
              SUM("Sales Amount") OVER (PARTITION BY Category) AS "Sales Amt per Cat"
       FROM df
       LIMIT 5
    """
).collect()

shape: (5, 3)
┌──────────┬─────────────┬───────────────────┐
│ Category ┆ Subcategory ┆ Sales Amt per Cat │
│ ---      ┆ ---         ┆ ---               │
│ str      ┆ str         ┆ f64               │
╞══════════╪═════════════╪═══════════════════╡
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
│ Audio    ┆ MP4&MP3     ┆ 238355.95         │
└──────────┴─────────────┴───────────────────┘

In [99]:
sales_by_cat.filter(pl.col('Category')=='Audio').unique().head()

shape: (3, 3)
┌──────────┬──────────────────────┬───────────────────┐
│ Category ┆ Subcategory          ┆ Sales Amt per Cat │
│ ---      ┆ ---                  ┆ ---               │
│ str      ┆ str                  ┆ f64               │
╞══════════╪══════════════════════╪═══════════════════╡
│ Audio    ┆ Bluetooth Headphones ┆ 238355.95         │
│ Audio    ┆ MP4&MP3              ┆ 238355.95         │
│ Audio    ┆ Recording Pen        ┆ 238355.95         │
└──────────┴──────────────────────┴───────────────────┘

In [102]:
df.select(pl.when(pl.col("Sales Amount") > 1000).then(pl.lit('High')).otherwise(pl.lit("Low")))

shape: (13_915, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ Low     │
│ Low     │
│ Low     │
│ Low     │
│ Low     │
│ …       │
│ Low     │
│ Low     │
│ Low     │
│ Low     │
│ Low     │
└─────────┘

In [103]:
df.shape, sales_by_cat.shape

((13915, 21), (13915, 3))

In [ ]:
df.sql(
    f"""
    SELECT DISTINCT Category, Brand, Subcategory,
           AVG("Sales Amount") OVER (PARTITION BY Category, Brand) AS "Avg Sales Amt per Cat and Brand"
    FROM SELF
    WHERE Category = 'Computers'
    ORDER BY Brand
    LIMIT 10
    """
)

shape: (10, 4)
┌───────────┬─────────────────┬──────────────────────────┬─────────────────────────────────┐
│ Category  ┆ Brand           ┆ Subcategory              ┆ Avg Sales Amt per Cat and Brand │
│ ---       ┆ ---             ┆ ---                      ┆ ---                             │
│ str       ┆ str             ┆ str                      ┆ f64                             │
╞═══════════╪═════════════════╪══════════════════════════╪═════════════════════════════════╡
│ Computers ┆ Adventure Works ┆ Laptops                  ┆ 1797.371618                     │
│ Computers ┆ Adventure Works ┆ Desktops                 ┆ 1797.371618                     │
│ Computers ┆ Adventure Works ┆ Monitors                 ┆ 1797.371618                     │
│ Computers ┆ Contoso         ┆ Projectors & Screens     ┆ 689.986461                      │
│ Computers ┆ Contoso         ┆ Computers Accessories    ┆ 689.986461                      │
│ Computers ┆ Fabrikam        ┆ Laptops                  ┆ 1982.065906                     │
│ Computers ┆ Proseware       ┆ Laptops                  ┆ 1095.304828                     │
│ Computers ┆ Proseware       ┆ Monitors                 ┆ 1095.304828                     │
│ Computers ┆ Proseware       ┆ Projectors & Screens     ┆ 1095.304828                     │
│ Computers ┆ Proseware       ┆ Printers, Scanners & Fax ┆ 1095.304828                     │
└───────────┴─────────────────┴──────────────────────────┴─────────────────────────────────┘

In [104]:
(
    df
    .select(
        'Category',
        'Brand',
        'Subcategory',
        pl.col('Sales Amount').mean().over('Category', 'Brand').alias('Avg Sales per Cat and Brand')
    )
    .filter(
        (pl.col('Category')=='Computers') 
    )
    .unique()
    .sort('Brand')
    .head(10)
)

shape: (10, 4)
┌───────────┬─────────────────┬──────────────────────────┬─────────────────────────────┐
│ Category  ┆ Brand           ┆ Subcategory              ┆ Avg Sales per Cat and Brand │
│ ---       ┆ ---             ┆ ---                      ┆ ---                         │
│ str       ┆ str             ┆ str                      ┆ f64                         │
╞═══════════╪═════════════════╪══════════════════════════╪═════════════════════════════╡
│ Computers ┆ Adventure Works ┆ Monitors                 ┆ 1797.371618                 │
│ Computers ┆ Adventure Works ┆ Laptops                  ┆ 1797.371618                 │
│ Computers ┆ Adventure Works ┆ Desktops                 ┆ 1797.371618                 │
│ Computers ┆ Contoso         ┆ Computers Accessories    ┆ 689.986461                  │
│ Computers ┆ Contoso         ┆ Projectors & Screens     ┆ 689.986461                  │
│ Computers ┆ Fabrikam        ┆ Laptops                  ┆ 1982.065906                 │
│ Computers ┆ Proseware       ┆ Printers, Scanners & Fax ┆ 1095.304828                 │
│ Computers ┆ Proseware       ┆ Monitors                 ┆ 1095.304828                 │
│ Computers ┆ Proseware       ┆ Projectors & Screens     ┆ 1095.304828                 │
│ Computers ┆ Proseware       ┆ Laptops                  ┆ 1095.304828                 │
└───────────┴─────────────────┴──────────────────────────┴─────────────────────────────┘

In [110]:
from datetime import date

curr_yr = date.today().year
cust_birth_yr = curr_yr - pl.col('Customer Age')

(
    df
    .select(
        'Category',
        'Brand',
        'Customer Age',
        pl.col('Sales Amount').mean().over('Category', cust_birth_yr).alias('Avg Sales per Cat') 
    )
    .filter(pl.col('Category')=='Computers')
    .unique()
    .sort('Customer Age')
    .head(10)
)

shape: (10, 4)
┌───────────┬──────────────────────┬──────────────┬───────────────────┐
│ Category  ┆ Brand                ┆ Customer Age ┆ Avg Sales per Cat │
│ ---       ┆ ---                  ┆ ---          ┆ ---               │
│ str       ┆ str                  ┆ i64          ┆ f64               │
╞═══════════╪══════════════════════╪══════════════╪═══════════════════╡
│ Computers ┆ Southridge Video     ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Wide World Importers ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Contoso              ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Proseware            ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Fabrikam             ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Adventure Works      ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Adventure Works      ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Fabrikam             ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Proseware            ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Contoso              ┆ 20           ┆ 2094.541406       │
└───────────┴──────────────────────┴──────────────┴───────────────────┘

In [111]:
curr_yr = date.today().year
ctx = pl.SQLContext(df=df)

result = ctx.execute(
    f"""
    SELECT DISTINCT
           Category,
           Brand,
           "Customer Age",
           AVG("Sales Amount") OVER (
               PARTITION BY Category, ({curr_yr} - "Customer Age")
           ) AS "Avg Sales per Cat"
    FROM df
    WHERE Category = 'Computers'
    ORDER BY "Customer Age"
    LIMIT 10
    """
).collect()

result

shape: (10, 4)
┌───────────┬──────────────────────┬──────────────┬───────────────────┐
│ Category  ┆ Brand                ┆ Customer Age ┆ Avg Sales per Cat │
│ ---       ┆ ---                  ┆ ---          ┆ ---               │
│ str       ┆ str                  ┆ i64          ┆ f64               │
╞═══════════╪══════════════════════╪══════════════╪═══════════════════╡
│ Computers ┆ Fabrikam             ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Adventure Works      ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Wide World Importers ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Proseware            ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Contoso              ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Southridge Video     ┆ 19           ┆ 1665.993158       │
│ Computers ┆ Fabrikam             ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Adventure Works      ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Wide World Importers ┆ 20           ┆ 2094.541406       │
│ Computers ┆ Proseware            ┆ 20           ┆ 2094.541406       │
└───────────┴──────────────────────┴──────────────┴───────────────────┘

In [112]:
(
    df
    .group_by('Category')
    .agg(pl.col('Sales Amount').max().alias('Max Sales Amt'))
    .with_columns(
        pl.col('Max Sales Amt').rank(descending=True).alias('Rank')
    )
    .sort('Rank')
)

shape: (8, 3)
┌───────────────────────────────┬───────────────┬──────┐
│ Category                      ┆ Max Sales Amt ┆ Rank │
│ ---                           ┆ ---           ┆ ---  │
│ str                           ┆ f64           ┆ f64  │
╞═══════════════════════════════╪═══════════════╪══════╡
│ TV and Video                  ┆ 28999.9       ┆ 1.0  │
│ Home Appliances               ┆ 28479.91      ┆ 2.0  │
│ Computers                     ┆ 19992.0       ┆ 3.0  │
│ Cameras and camcorders        ┆ 10810.8       ┆ 4.0  │
│ Cell phones                   ┆ 5183.2        ┆ 5.0  │
│ Music, Movies and Audio Books ┆ 3041.88       ┆ 6.0  │
│ Audio                         ┆ 2871.2        ┆ 7.0  │
│ Games and Toys                ┆ 2813.16       ┆ 8.0  │
└───────────────────────────────┴───────────────┴──────┘

In [115]:
ctx.execute(
    f"""
    WITH cat_max AS (
        SELECT Category,
               MAX("Sales Amount") AS "Max Sales Amt"
        FROM df
        GROUP BY Category
    )
    SELECT Category,
        "Max Sales Amt",
        CAST(
            RANK() OVER (
                ORDER BY "Max Sales Amt" DESC
            ) + (
                COUNT(*) OVER (PARTITION BY "Max Sales Amt") - 1
            ) / 2.0 AS DOUBLE
        ) AS "Rank"
    FROM cat_max
    ORDER BY "Rank"
    """
).collect()

shape: (8, 3)
┌───────────────────────────────┬───────────────┬──────┐
│ Category                      ┆ Max Sales Amt ┆ Rank │
│ ---                           ┆ ---           ┆ ---  │
│ str                           ┆ f64           ┆ f64  │
╞═══════════════════════════════╪═══════════════╪══════╡
│ TV and Video                  ┆ 28999.9       ┆ 1.0  │
│ Home Appliances               ┆ 28479.91      ┆ 2.0  │
│ Computers                     ┆ 19992.0       ┆ 3.0  │
│ Cameras and camcorders        ┆ 10810.8       ┆ 4.0  │
│ Cell phones                   ┆ 5183.2        ┆ 5.0  │
│ Music, Movies and Audio Books ┆ 3041.88       ┆ 6.0  │
│ Audio                         ┆ 2871.2        ┆ 7.0  │
│ Games and Toys                ┆ 2813.16       ┆ 8.0  │
└───────────────────────────────┴───────────────┴──────┘

In [116]:
(
    df
    .group_by('Category', 'Subcategory')
    .agg(pl.col('Sales Amount').max().round().cast(pl.Int64).alias('Max Sales Amt'))
    .with_columns(
        pl.col('Max Sales Amt').rank(descending=True).over('Category').cast(pl.Int64).alias('Rank')
    )
    .filter(pl.col('Category').is_in(['Audio', 'Computers']))
    .sort(['Category', 'Rank'])
)

shape: (9, 4)
┌───────────┬──────────────────────────┬───────────────┬──────┐
│ Category  ┆ Subcategory              ┆ Max Sales Amt ┆ Rank │
│ ---       ┆ ---                      ┆ ---           ┆ ---  │
│ str       ┆ str                      ┆ i64           ┆ i64  │
╞═══════════╪══════════════════════════╪═══════════════╪══════╡
│ Audio     ┆ Recording Pen            ┆ 2871          ┆ 1    │
│ Audio     ┆ Bluetooth Headphones     ┆ 2250          ┆ 2    │
│ Audio     ┆ MP4&MP3                  ┆ 2095          ┆ 3    │
│ Computers ┆ Projectors & Screens     ┆ 19992         ┆ 1    │
│ Computers ┆ Laptops                  ┆ 19485         ┆ 2    │
│ Computers ┆ Desktops                 ┆ 14535         ┆ 3    │
│ Computers ┆ Monitors                 ┆ 11425         ┆ 4    │
│ Computers ┆ Printers, Scanners & Fax ┆ 2508          ┆ 5    │
│ Computers ┆ Computers Accessories    ┆ 2424          ┆ 6    │
└───────────┴──────────────────────────┴───────────────┴──────┘

In [ ]:
ctx = pl.SQLContext(df=df)

result = ctx.execute(
    """
    WITH subcat_max AS (
        SELECT Category,
               Subcategory,
               CAST(
                   ROUND(MAX("Sales Amount"), 0) AS BIGINT
               ) AS "Max Sales Amt"
        FROM df
        WHERE Category IN ('Audio', 'Computers')
        GROUP BY Category, Subcategory
    )
    SELECT Category,
        Subcategory,
        "Max Sales Amt",
        CAST(
            RANK() OVER (
                PARTITION BY Category
                ORDER BY "Max Sales Amt" DESC
            )
            + (
                COUNT(*) OVER (
                    PARTITION BY Category, "Max Sales Amt"
                ) - 1
            ) / 2.0
            AS BIGINT
        ) AS "Rank"
    FROM subcat_max
    ORDER BY Category, "Rank"
    """
).collect()
result

shape: (9, 4)
┌───────────┬──────────────────────────┬───────────────┬──────┐
│ Category  ┆ Subcategory              ┆ Max Sales Amt ┆ Rank │
│ ---       ┆ ---                      ┆ ---           ┆ ---  │
│ str       ┆ str                      ┆ i64           ┆ i64  │
╞═══════════╪══════════════════════════╪═══════════════╪══════╡
│ Audio     ┆ Recording Pen            ┆ 2871          ┆ 1    │
│ Audio     ┆ Bluetooth Headphones     ┆ 2250          ┆ 2    │
│ Audio     ┆ MP4&MP3                  ┆ 2095          ┆ 3    │
│ Computers ┆ Projectors & Screens     ┆ 19992         ┆ 1    │
│ Computers ┆ Laptops                  ┆ 19485         ┆ 2    │
│ Computers ┆ Desktops                 ┆ 14535         ┆ 3    │
│ Computers ┆ Monitors                 ┆ 11425         ┆ 4    │
│ Computers ┆ Printers, Scanners & Fax ┆ 2508          ┆ 5    │
│ Computers ┆ Computers Accessories    ┆ 2424          ┆ 6    │
└───────────┴──────────────────────────┴───────────────┴──────┘

### There is more...

In [126]:
max_sales_rank = (
    df
    .group_by('Category', 'Subcategory')
    .agg(pl.col('Sales Amount').max().round().cast(pl.Int64).alias('Max Sales Amt'))
    .with_columns(
        pl.col('Max Sales Amt').rank(descending=True).over('Category').cast(pl.Int64).alias('Rank')
    )
    .filter(pl.col('Category').is_in(['Audio', 'Computers']))
    .sort(['Category', 'Rank'])
)

In [127]:
max_sales_rank.with_columns(
    pl.col('Subcategory')
    .sort_by('Max Sales Amt')
    .head(3)
    .over('Category', mapping_strategy='join')
    .alias('Lowest 3 Subcat per Cat')
)

shape: (9, 5)
┌───────────┬──────────────────────────┬───────────────┬──────┬────────────────────────────────┐
│ Category  ┆ Subcategory              ┆ Max Sales Amt ┆ Rank ┆ Lowest 3 Subcat per Cat        │
│ ---       ┆ ---                      ┆ ---           ┆ ---  ┆ ---                            │
│ str       ┆ str                      ┆ i64           ┆ i64  ┆ list[str]                      │
╞═══════════╪══════════════════════════╪═══════════════╪══════╪════════════════════════════════╡
│ Audio     ┆ Recording Pen            ┆ 2871          ┆ 1    ┆ ["MP4&MP3", "Bluetooth         │
│           ┆                          ┆               ┆      ┆ Headphones", "Recording Pen…   │
│ Audio     ┆ Bluetooth Headphones     ┆ 2250          ┆ 2    ┆ ["MP4&MP3", "Bluetooth         │
│           ┆                          ┆               ┆      ┆ Headphones", "Recording Pen…   │
│ Audio     ┆ MP4&MP3                  ┆ 2095          ┆ 3    ┆ ["MP4&MP3", "Bluetooth         │
│           ┆                          ┆               ┆      ┆ Headphones", "Recording Pen…   │
│ Computers ┆ Projectors & Screens     ┆ 19992         ┆ 1    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
│ Computers ┆ Laptops                  ┆ 19485         ┆ 2    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
│ Computers ┆ Desktops                 ┆ 14535         ┆ 3    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
│ Computers ┆ Monitors                 ┆ 11425         ┆ 4    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
│ Computers ┆ Printers, Scanners & Fax ┆ 2508          ┆ 5    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
│ Computers ┆ Computers Accessories    ┆ 2424          ┆ 6    ┆ ["Computers Accessories",      │
│           ┆                          ┆               ┆      ┆ "Printers, Scanners & Fa…      │
└───────────┴──────────────────────────┴───────────────┴──────┴────────────────────────────────┘

In [125]:
max_sales_rank.with_columns(
    pl.col('Subcategory')
    .sort_by('Max Sales Amt')
    .over('Category', mapping_strategy='explode')
    .alias('Subcategory Sorted by Max Sales Amt Ascending')
)

shape: (9, 5)
┌───────────┬──────────────────────────┬───────────────┬──────┬─────────────────────────────────┐
│ Category  ┆ Subcategory              ┆ Max Sales Amt ┆ Rank ┆ Subcategory Sorted by Max Sales │
│ ---       ┆ ---                      ┆ ---           ┆ ---  ┆ Amt Ascending                   │
│ str       ┆ str                      ┆ i64           ┆ i64  ┆ ---                             │
│           ┆                          ┆               ┆      ┆ str                             │
╞═══════════╪══════════════════════════╪═══════════════╪══════╪═════════════════════════════════╡
│ Audio     ┆ Recording Pen            ┆ 2871          ┆ 1    ┆ MP4&MP3                         │
│ Audio     ┆ Bluetooth Headphones     ┆ 2250          ┆ 2    ┆ Bluetooth Headphones            │
│ Audio     ┆ MP4&MP3                  ┆ 2095          ┆ 3    ┆ Recording Pen                   │
│ Computers ┆ Projectors & Screens     ┆ 19992         ┆ 1    ┆ Computers Accessories           │
│ Computers ┆ Laptops                  ┆ 19485         ┆ 2    ┆ Printers, Scanners & Fax        │
│ Computers ┆ Desktops                 ┆ 14535         ┆ 3    ┆ Monitors                        │
│ Computers ┆ Monitors                 ┆ 11425         ┆ 4    ┆ Desktops                        │
│ Computers ┆ Printers, Scanners & Fax ┆ 2508          ┆ 5    ┆ Laptops                         │
│ Computers ┆ Computers Accessories    ┆ 2424          ┆ 6    ┆ Projectors & Screens            │
└───────────┴──────────────────────────┴───────────────┴──────┴─────────────────────────────────┘

In [130]:
(
    max_sales_rank
    .sort('Subcategory')
    .with_columns(
        pl.col('Subcategory')
        .sort_by('Max Sales Amt')
        .over('Category', mapping_strategy='explode')
        .alias('Subcategory Sorted by Max Sales Amt Ascending')
    )
)

shape: (9, 5)
┌───────────┬──────────────────────────┬───────────────┬──────┬─────────────────────────────────┐
│ Category  ┆ Subcategory              ┆ Max Sales Amt ┆ Rank ┆ Subcategory Sorted by Max Sales │
│ ---       ┆ ---                      ┆ ---           ┆ ---  ┆ Amt Ascending                   │
│ str       ┆ str                      ┆ i64           ┆ i64  ┆ ---                             │
│           ┆                          ┆               ┆      ┆ str                             │
╞═══════════╪══════════════════════════╪═══════════════╪══════╪═════════════════════════════════╡
│ Audio     ┆ Bluetooth Headphones     ┆ 2250          ┆ 2    ┆ MP4&MP3                         │
│ Computers ┆ Computers Accessories    ┆ 2424          ┆ 6    ┆ Bluetooth Headphones            │
│ Computers ┆ Desktops                 ┆ 14535         ┆ 3    ┆ Recording Pen                   │
│ Computers ┆ Laptops                  ┆ 19485         ┆ 2    ┆ Computers Accessories           │
│ Audio     ┆ MP4&MP3                  ┆ 2095          ┆ 3    ┆ Printers, Scanners & Fax        │
│ Computers ┆ Monitors                 ┆ 11425         ┆ 4    ┆ Monitors                        │
│ Computers ┆ Printers, Scanners & Fax ┆ 2508          ┆ 5    ┆ Desktops                        │
│ Computers ┆ Projectors & Screens     ┆ 19992         ┆ 1    ┆ Laptops                         │
│ Audio     ┆ Recording Pen            ┆ 2871          ┆ 1    ┆ Projectors & Screens            │
└───────────┴──────────────────────────┴───────────────┴──────┴─────────────────────────────────┘

## Applying UDFs

### How to do it...

In [10]:
import polars as pl

In [131]:
df = pl.read_csv('../data/contoso_sales.csv', try_parse_dates=True)
df.head()

shape: (5, 20)
┌────────┬────────┬─────────────┬─────────────┬───┬─────────────┬───────┬─────────────┬────────────┐
│ Order  ┆ Line   ┆ Order Date  ┆ Delivery    ┆ … ┆ Net Price   ┆ Unit  ┆ Currency    ┆ Exchange   │
│ Number ┆ Number ┆ ---         ┆ Date        ┆   ┆ ---         ┆ Cost  ┆ Code        ┆ Rate       │
│ ---    ┆ ---    ┆ date        ┆ ---         ┆   ┆ f64         ┆ ---   ┆ ---         ┆ ---        │
│ i64    ┆ i64    ┆             ┆ date        ┆   ┆             ┆ f64   ┆ str         ┆ f64        │
╞════════╪════════╪═════════════╪═════════════╪═══╪═════════════╪═══════╪═════════════╪════════════╡
│ 284806 ┆ 1      ┆ 2017-10-18  ┆ 2017-10-20  ┆ … ┆ 10.288      ┆ 5.958 ┆ USD         ┆ 1.0        │
│ 285506 ┆ 1      ┆ 2017-10-25  ┆ 2017-10-26  ┆ … ┆ 11.691      ┆ 5.958 ┆ AUD         ┆ 1.2967     │
│ 311002 ┆ 2      ┆ 2018-07-07  ┆ 2018-07-12  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.3484     │
│ 366307 ┆ 2      ┆ 2020-01-11  ┆ 2020-01-11  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.4545     │
│ 325708 ┆ 3      ┆ 2018-12-01  ┆ 2018-12-02  ┆ … ┆ 11.5611     ┆ 6.62  ┆ USD         ┆ 1.0        │
└────────┴────────┴─────────────┴─────────────┴───┴─────────────┴───────┴─────────────┴────────────┘

In [132]:
def get_first_name(full_name: str) -> str:
    return full_name.split(' ')[0]

In [139]:
%%timeit 1
df.select(
    'Customer Name',
    pl.col('Customer Name').map_elements(lambda el: get_first_name(el), return_dtype=pl.String).alias('Customer First Name')
).head()

6.33 ms ± 130 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [140]:
%%timeit 1
df.select(
    'Customer Name',
    pl.col('Customer Name').str.split(' ').list.first().alias('Customer First Name')
).head()

570 μs ± 13.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [142]:
%%timeit 1
df.select(
    'Customer Name',
    pl.col('Customer Name').map_elements(lambda el: el.split(' ')[0], return_dtype=pl.String).alias('Customer First Name')
).head()

5.68 ms ± 144 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [146]:
def age_to_range(age: int) -> str:
    if age < 18:
        return '~17'
    elif age <= 30:
        return '18~30'
    elif age <= 50:
        return '31~50'
    elif age <= 70:
        return '51~70'
    else:
        return '71~'

In [147]:
%%timeit 1
df.select(
    'Customer Age',
    pl.col('Customer Age').map_elements(lambda el: age_to_range(el), return_dtype=pl.String).alias('Age Range')
).head()

3.65 ms ± 73 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [145]:
%%timeit 1
age = pl.col("Customer Age")

df.select(
    "Customer Age",
    pl.when(age.is_null())
    .then(pl.lit(None, dtype=pl.String))
    .when(age < 18)
    .then(pl.lit("~17"))
    .when(age <= 30)
    .then(pl.lit("18~30"))
    .when(age <= 50)
    .then(pl.lit("31~50"))
    .when(age <= 70)
    .then(pl.lit("51~70"))
    .otherwise(pl.lit("71~"))
    .alias("Age Range"),
).head()

440 μs ± 25.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [151]:
%%timeit 1
def ages_to_ranges(ages: pl.Series) -> pl.Series:
    return ages.to_frame("age").select(
        pl.when(pl.col("age").is_null())
        .then(pl.lit(None, dtype=pl.String))
        .when(pl.col("age") < 18)
        .then(pl.lit("~17"))
        .when(pl.col("age") <= 30)
        .then(pl.lit("18~30"))
        .when(pl.col("age") <= 50)
        .then(pl.lit("31~50"))
        .when(pl.col("age") <= 70)
        .then(pl.lit("50~70"))
        .otherwise(pl.lit("71~"))
        .alias("Age Range")
    ).to_series()


df.select(
    "Customer Age",
    pl.col("Customer Age")
    .map_batches(
        ages_to_ranges,
        return_dtype=pl.String,
        is_elementwise=True,
    )
    .alias("Age Range"),
).head()

1.74 ms ± 30.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

### There is more...

In [152]:
df.select(
    'Customer Name',
    pl.col('Customer Name').str.split(' ').list.first().alias('Customer First Name')
).head()

shape: (5, 2)
┌───────────────┬─────────────────────┐
│ Customer Name ┆ Customer First Name │
│ ---           ┆ ---                 │
│ str           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ Eric Kennedy  ┆ Eric                │
│ George Tooth  ┆ George              │
│ Caleb Greene  ┆ Caleb               │
│ Isaac Siddins ┆ Isaac               │
│ Mike McQueen  ┆ Mike                │
└───────────────┴─────────────────────┘

In [153]:
df.select(
    'Customer Age',
    pl.when(pl.col('Customer Age')<18).then(pl.lit('~17'))
    .when(pl.col('Customer Age')<=30).then(pl.lit('18~30'))
    .when(pl.col('Customer Age')<=50).then(pl.lit('31~50'))
    .when(pl.col('Customer Age')<=70).then(pl.lit('51~70'))
    .when(pl.col('Customer Age')>70).then(pl.lit('71~'))
    .alias('Age Range')
).head()

shape: (5, 2)
┌──────────────┬───────────┐
│ Customer Age ┆ Age Range │
│ ---          ┆ ---       │
│ i64          ┆ str       │
╞══════════════╪═══════════╡
│ 47           ┆ 31~50     │
│ 30           ┆ 18~30     │
│ 59           ┆ 51~70     │
│ 25           ┆ 18~30     │
│ 56           ┆ 51~70     │
└──────────────┴───────────┘

In [ ]:
%%timeit
df.select(
    'Customer Name',
    pl.col('Customer Name').map_elements(lambda el: el.split(' ')[0], return_dtype=pl.String).alias('Customer First Name')
).head()

In [ ]:
%%timeit
df.select(
    'Customer Name',
    pl.col('Customer Name').str.split(' ').list.first().alias('Customer First Name')
).head()

## Using SQL for data transformations

In [154]:
import polars as pl
df = pl.read_csv('../data/contoso_sales.csv', try_parse_dates=True)
df.head()

shape: (5, 20)
┌────────┬────────┬─────────────┬─────────────┬───┬─────────────┬───────┬─────────────┬────────────┐
│ Order  ┆ Line   ┆ Order Date  ┆ Delivery    ┆ … ┆ Net Price   ┆ Unit  ┆ Currency    ┆ Exchange   │
│ Number ┆ Number ┆ ---         ┆ Date        ┆   ┆ ---         ┆ Cost  ┆ Code        ┆ Rate       │
│ ---    ┆ ---    ┆ date        ┆ ---         ┆   ┆ f64         ┆ ---   ┆ ---         ┆ ---        │
│ i64    ┆ i64    ┆             ┆ date        ┆   ┆             ┆ f64   ┆ str         ┆ f64        │
╞════════╪════════╪═════════════╪═════════════╪═══╪═════════════╪═══════╪═════════════╪════════════╡
│ 284806 ┆ 1      ┆ 2017-10-18  ┆ 2017-10-20  ┆ … ┆ 10.288      ┆ 5.958 ┆ USD         ┆ 1.0        │
│ 285506 ┆ 1      ┆ 2017-10-25  ┆ 2017-10-26  ┆ … ┆ 11.691      ┆ 5.958 ┆ AUD         ┆ 1.2967     │
│ 311002 ┆ 2      ┆ 2018-07-07  ┆ 2018-07-12  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.3484     │
│ 366307 ┆ 2      ┆ 2020-01-11  ┆ 2020-01-11  ┆ … ┆ 12.99       ┆ 6.62  ┆ AUD         ┆ 1.4545     │
│ 325708 ┆ 3      ┆ 2018-12-01  ┆ 2018-12-02  ┆ … ┆ 11.5611     ┆ 6.62  ┆ USD         ┆ 1.0        │
└────────┴────────┴─────────────┴─────────────┴───┴─────────────┴───────┴─────────────┴────────────┘

### How to do it...

In [155]:
ctx = pl.SQLContext(eager=True)
ctx.register('df', df)
ctx.execute(
    """
      select
        `Customer Name`,
        Brand,
        Category
      from df limit 5
    """
)

shape: (5, 3)
┌───────────────┬─────────┬──────────┐
│ Customer Name ┆ Brand   ┆ Category │
│ ---           ┆ ---     ┆ ---      │
│ str           ┆ str     ┆ str      │
╞═══════════════╪═════════╪══════════╡
│ Eric Kennedy  ┆ Contoso ┆ Audio    │
│ George Tooth  ┆ Contoso ┆ Audio    │
│ Caleb Greene  ┆ Contoso ┆ Audio    │
│ Isaac Siddins ┆ Contoso ┆ Audio    │
│ Mike McQueen  ┆ Contoso ┆ Audio    │
└───────────────┴─────────┴──────────┘

In [156]:
ctx.execute(
    """
      select
        Brand,
        avg(Quantity) as `Avg Quantity` 
      from df
      group by 
        Brand
      order by 
        `Avg Quantity` desc
      limit 5
    """
)

shape: (5, 2)
┌──────────────────────┬──────────────┐
│ Brand                ┆ Avg Quantity │
│ ---                  ┆ ---          │
│ str                  ┆ f64          │
╞══════════════════════╪══════════════╡
│ Fabrikam             ┆ 3.225532     │
│ Northwind Traders    ┆ 3.222222     │
│ Wide World Importers ┆ 3.193811     │
│ Fabrikam             ┆ 3.192308     │
│ Southridge Video     ┆ 3.189509     │
└──────────────────────┴──────────────┘

In [37]:
pl.SQLContext(lf=df.lazy()).execute(
    """
        select 
            Brand,
            Category
        from lf
        limit 5
    """
).collect()

shape: (5, 2)
┌─────────┬──────────┐
│ Brand   ┆ Category │
│ ---     ┆ ---      │
│ str     ┆ str      │
╞═════════╪══════════╡
│ Contoso ┆ Audio    │
│ Contoso ┆ Audio    │
│ Contoso ┆ Audio    │
│ Contoso ┆ Audio    │
│ Contoso ┆ Audio    │
└─────────┴──────────┘