# Chapter 7: Working with Nested Data Structures

## Technical Requirements

In [1]:
import polars as pl

In [3]:
df = pl.read_csv("../data/us_videos.csv", try_parse_dates=True)
df.glimpse(max_items_per_column=2)

Rows: 40949
Columns: 16
$ video_id                             <str> '2kyS6SvSYSE', '1ZAPwfrtAFY'
$ trending_date                        <str> '17.14.11', '17.14.11'
$ title                                <str> 'WE WANT TO TALK ABOUT OUR MARRIAGE', 'The Trump Presidency: Last Week Tonight with John Oliver (HBO)'
$ channel_title                        <str> 'CaseyNeistat', 'LastWeekTonight'
$ category_id                          <i64> 22, 24
$ publish_time           <datetime[μs, UTC]> 2017-11-13 17:13:01+00:00, 2017-11-13 07:30:00+00:00
$ tags                                 <str> 'SHANtell martin', 'last week tonight trump presidency|last week tonight donald trump|john oliver trump|donald trump'
$ views                                <i64> 748374, 2418783
$ likes                                <i64> 57527, 97185
$ dislikes                             <i64> 2966, 6146
$ comment_count                        <i64> 15954, 12703
$ thumbnail_link                       <str> 'https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg', 'https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg'
$ comments_disabled                   <bool> False, False
$ ratings_disabled                    <bool> False, False
$ video_error_or_removed              <bool> False, False
$ description                          <str> "SHANTELL'S CHANNEL - https://www.youtube.com/shantellmartin\\nCANDICE - https://www.lovebilly.com\\n\\nfilmed this video in 4k on this -- http://amzn.to/2sTDnRZ\\nwith this lens -- http://amzn.to/2rUJOmD\\nbig drone - http://tinyurl.com/h4ft3oy\\nOTHER GEAR ---  http://amzn.to/2o3GLX5\\nSony CAMERA http://amzn.to/2nOBmnv\\nOLD CAMERA; http://amzn.to/2o2cQBT\\nMAIN LENS; http://amzn.to/2od5gBJ\\nBIG SONY CAMERA; http://amzn.to/2nrdJRO\\nBIG Canon CAMERA; http://tinyurl.com/jn4q4vz\\nBENDY TRIPOD THING; http://tinyurl.com/gw3ylz2\\nYOU NEED THIS FOR THE BENDY TRIPOD; http://tinyurl.com/j8mzzua\\nWIDE LENS; http://tinyurl.com/jkfcm8t\\nMORE EXPENSIVE WIDE LENS; http://tinyurl.com/zrdgtou\\nSMALL CAMERA; http://tinyurl.com/hrrzhor\\nMICROPHONE; http://tinyurl.com/zefm4jy\\nOTHER MICROPHONE; http://tinyurl.com/jxgpj86\\nOLD DRONE (cheaper but still great);http://tinyurl.com/zcfmnmd\\n\\nfollow me; on http://instagram.com/caseyneistat\\non https://www.facebook.com/cneistat\\non https://twitter.com/CaseyNeistat\\n\\namazing intro song by https://soundcloud.com/discoteeth\\n\\nad disclosure.  THIS IS NOT AN AD.  not selling or promoting anything.  but samsung did produce the Shantell Video as a 'GALAXY PROJECT' which is an initiative that enables creators like Shantell and me to make projects we might otherwise not have the opportunity to make.  hope that's clear.  if not ask in the comments and i'll answer any specifics.", "One year after the presidential election, John Oliver discusses what we've learned so far and enlists our catheter cowboy to teach Donald Trump what he hasn't.\\n\\nConnect with Last Week Tonight online...\\n\\nSubscribe to the Last Week Tonight YouTube channel for more almost news as it almost happens: www.youtube.com/user/LastWeekTonight\\n\\nFind Last Week Tonight on Facebook like your mom would: http://Facebook.com/LastWeekTonight\\n\\nFollow us on Twitter for news about jokes and jokes about news: http://Twitter.com/LastWeekTonight\\n\\nVisit our official site for all that other stuff at once: http://www.hbo.com/lastweektonight"

In [ ]:
df.head()

In [4]:
df = df.with_columns(pl.col("trending_date").str.to_date(format="%y.%d.%m"))

In [5]:
df.select('trending_date').dtypes[0]

Date

## Creating lists

### How to do it...

In [6]:
df.select(
    'tags',
    pl.col('tags').str.split('|').alias('tags in list')
).head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ tags                            ┆ tags in list                    │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ SHANtell martin                 ┆ ["SHANtell martin"]             │
│ last week tonight trump presid… ┆ ["last week tonight trump pres… │
│ racist superman|rudy|mancuso|k… ┆ ["racist superman", "rudy", … … │
│ rhett and link|gmm|good mythic… ┆ ["rhett and link", "gmm", … "c… │
│ ryan|higa|higatv|nigahiga|i da… ┆ ["ryan", "higa", … "fail"]      │
└─────────────────────────────────┴─────────────────────────────────┘

In [7]:
(
    df
    .group_by('trending_date')
    .agg(pl.col('video_id'))
    .sort('trending_date', descending=True)
).head()

shape: (5, 2)
┌───────────────┬─────────────────────────────────┐
│ trending_date ┆ video_id                        │
│ ---           ┆ ---                             │
│ date          ┆ list[str]                       │
╞═══════════════╪═════════════════════════════════╡
│ 2018-06-14    ┆ ["-QPdRfqTnt4", "gPHVLxm8U-0",… │
│ 2018-06-13    ┆ ["FchkqXEg0qs", "uHRwMmwbFnA",… │
│ 2018-06-12    ┆ ["PPWDwBrUNyY", "rAH8qm5oQHg",… │
│ 2018-06-11    ┆ ["0bXCbVGb04A", "L4pkD78oKSo",… │
│ 2018-06-10    ┆ ["L4pkD78oKSo", "ZFwylDNpgFc",… │
└───────────────┴─────────────────────────────────┘

In [8]:
df.select(
    pl.concat_list(
        pl.col('views'),
        pl.col('likes'),
        pl.col('dislikes'),
        pl.col('comment_count')
    ).alias('engagement')
).head()

shape: (5, 1)
┌────────────────────────────┐
│ engagement                 │
│ ---                        │
│ list[i64]                  │
╞════════════════════════════╡
│ [748374, 57527, … 15954]   │
│ [2418783, 97185, … 12703]  │
│ [3191434, 146033, … 8181]  │
│ [343168, 10172, … 2146]    │
│ [2095731, 132235, … 17518] │
└────────────────────────────┘

### There is more...

In [ ]:
df = pl.DataFrame({
    'nested_list': [
        [
            [1,2,3], [4,5,6], 
            [7,8,9], [10,11,12]
        ], 
        [
            [1,2,3], [4,5,6], 
            [7,8,9], [10,11,12]
        ]
    ]
})

In [ ]:
df

In [ ]:
df = pl.DataFrame({
    'nested_list': [
        [
            ['a',2,3], [4,5,6], 
            [7,8,9], [10,11,12]
        ], 
        [
            [1,2,3], [4,5,6], 
            [7,8,9], [10,11,12]
        ]
    ]
}, strict=False)

In [ ]:
df

## Aggregating elements in lists

### How to do it...

In [ ]:
import polars as pl

In [9]:
df = (
    pl.scan_csv('../data/us_videos.csv', try_parse_dates=True)
    .with_columns(
        pl.col('trending_date').str.to_date(format='%y.%d.%m')
    ).collect()
)
df.head()

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ video_id  ┆ trending_ ┆ title     ┆ channel_t ┆ … ┆ comments_ ┆ ratings_d ┆ video_err ┆ descript │
│ ---       ┆ date      ┆ ---       ┆ itle      ┆   ┆ disabled  ┆ isabled   ┆ or_or_rem ┆ ion      │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ oved      ┆ ---      │
│           ┆ date      ┆           ┆ str       ┆   ┆ bool      ┆ bool      ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2kyS6SvSY ┆ 2017-11-1 ┆ WE WANT   ┆ CaseyNeis ┆ … ┆ false     ┆ false     ┆ false     ┆ SHANTELL │
│ SE        ┆ 4         ┆ TO TALK   ┆ tat       ┆   ┆           ┆           ┆           ┆ 'S       │
│           ┆           ┆ ABOUT OUR ┆           ┆   ┆           ┆           ┆           ┆ CHANNEL  │
│           ┆           ┆ MARR…     ┆           ┆   ┆           ┆           ┆           ┆ - https: │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ //w…     │
│ 1ZAPwfrtA ┆ 2017-11-1 ┆ The Trump ┆ LastWeekT ┆ … ┆ false     ┆ false     ┆ false     ┆ One year │
│ FY        ┆ 4         ┆ Presidenc ┆ onight    ┆   ┆           ┆           ┆           ┆ after    │
│           ┆           ┆ y: Last   ┆           ┆   ┆           ┆           ┆           ┆ the pres │
│           ┆           ┆ Wee…      ┆           ┆   ┆           ┆           ┆           ┆ identia… │
│ 5qpjK5DgC ┆ 2017-11-1 ┆ Racist    ┆ Rudy      ┆ … ┆ false     ┆ false     ┆ false     ┆ WATCH MY │
│ t4        ┆ 4         ┆ Superman  ┆ Mancuso   ┆   ┆           ┆           ┆           ┆ PREVIOUS │
│           ┆           ┆ | Rudy    ┆           ┆   ┆           ┆           ┆           ┆ VIDEO ▶  │
│           ┆           ┆ Mancuso…  ┆           ┆   ┆           ┆           ┆           ┆ \n\n…    │
│ puqaWrEC7 ┆ 2017-11-1 ┆ Nickelbac ┆ Good      ┆ … ┆ false     ┆ false     ┆ false     ┆ Today we │
│ tY        ┆ 4         ┆ k Lyrics: ┆ Mythical  ┆   ┆           ┆           ┆           ┆ find out │
│           ┆           ┆ Real or   ┆ Morning   ┆   ┆           ┆           ┆           ┆ if Link  │
│           ┆           ┆ Fak…      ┆           ┆   ┆           ┆           ┆           ┆ is a…    │
│ d380meD0W ┆ 2017-11-1 ┆ I Dare    ┆ nigahiga  ┆ … ┆ false     ┆ false     ┆ false     ┆ I know   │
│ 0M        ┆ 4         ┆ You:      ┆           ┆   ┆           ┆           ┆           ┆ it's     │
│           ┆           ┆ GOING     ┆           ┆   ┆           ┆           ┆           ┆ been a   │
│           ┆           ┆ BALD!?    ┆           ┆   ┆           ┆           ┆           ┆ while    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ since…   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
agg_df = (
    df
    .group_by('trending_date')
    .agg(
        'views',
        'likes',
        'dislikes',
        'comment_count'
    )
    .sort('trending_date', descending=True)
)
agg_df.head()

shape: (5, 5)
┌───────────────┬────────────────────┬────────────────────┬────────────────────┬───────────────────┐
│ trending_date ┆ views              ┆ likes              ┆ dislikes           ┆ comment_count     │
│ ---           ┆ ---                ┆ ---                ┆ ---                ┆ ---               │
│ date          ┆ list[i64]          ┆ list[i64]          ┆ list[i64]          ┆ list[i64]         │
╞═══════════════╪════════════════════╪════════════════════╪════════════════════╪═══════════════════╡
│ 2018-06-14    ┆ [4427381, 5829270, ┆ [96391, 87323, …   ┆ [5508, 3668, …     ┆ [12726, 11933, …  │
│               ┆ … 10306119]        ┆ 357079]            ┆ 212976]            ┆ 144795]           │
│ 2018-06-13    ┆ [3238183, 470844,  ┆ [61841, 13922, …   ┆ [3708, 402, …      ┆ [0, 4843, …       │
│               ┆ … 7839668]         ┆ 352352]            ┆ 5871]              ┆ 46624]            │
│ 2018-06-12    ┆ [3483553, 6173038, ┆ [23725, 90478, …   ┆ [3145, 3877, …     ┆ [462, 7726, …     │
│               ┆ … 13619534]        ┆ 347100]            ┆ 6923]              ┆ 19977]            │
│ 2018-06-11    ┆ [2341772, 846887,  ┆ [140374, 5758, …   ┆ [2951, 850, …      ┆ [33760, 1539, …   │
│               ┆ … 6995168]         ┆ 143678]            ┆ 10925]             ┆ 17444]            │
│ 2018-06-10    ┆ [594004, 1504564,  ┆ [4470, 32430, …    ┆ [520, 4316, …      ┆ [1195, 6105, …    │
│               ┆ … 6980540]         ┆ 143452]            ┆ 10911]             ┆ 17429]            │
└───────────────┴────────────────────┴────────────────────┴────────────────────┴───────────────────┘

In [ ]:
df_pd = df.to_pandas()

In [ ]:
agg_df_pd = (
    df_pd.groupby('trending_date').agg(
        {'views': list, 'likes': list, 'dislikes': list, 'comment_count': list}
    ).sort_values('trending_date', ascending=False)
)

In [ ]:
agg_df_pd.transform({'views': len}).rename(columns={'views': 'views_count'})

In [ ]:
(
    agg_df
    .select(
        'trending_date',
        pl.col('views').list.min().alias('views_min'),
        pl.col('likes').list.max().alias('likes_max'),
        pl.col('dislikes').list.mean().alias('dislikes_mean'),
        pl.col('comment_count').list.sum().alias('comment_sum'),
    )
    .sort('trending_date', descending=True)
).head()

In [ ]:
(
    df
    .group_by('trending_date')
    .agg(pl.col('channel_title'))
    .with_columns(
        pl.col('channel_title').list.join(':')
    )
    .sort('trending_date', descending=True)
).head()

### There is more...

In [ ]:
(
    agg_df
    .select(
        'trending_date',
        pl.col('views').list.len().alias('item_cnt')
    )
).head()

## Accessing and selecting elements in lists

### Getting ready

In [ ]:
import polars as pl

In [ ]:
trending_dates_by_channel = (
    df
    .group_by('channel_title')
    .agg('trending_date')
    .with_columns(pl.col('trending_date').list.sort())
)

In [ ]:
trending_dates_by_channel.head()

### How to do it...

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col('trending_date').list.first().alias('first_trending_date'),
    pl.col('trending_date').list.last().alias('last_trending_date')
).head()

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col('trending_date').list.get(7, null_on_oob=True).alias('8th_element')
).head()

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col('trending_date').list.head().alias('first_5'),
    pl.col('trending_date').list.tail(10).alias('last_10')
).head()

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col('trending_date')
    .list.sort(descending=True)
    .list.head(3)
    .alias('3_most_recent_dates')
).head()

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col('trending_date')
    .list.sort(descending=True)
    .list.head(3)
    .alias('3_most_recent_dates')
).head()

In [ ]:
trending_dates_by_channel.select(
    'trending_date',
    pl.col('trending_date').list.slice(0, 2).alias('first_2_dates'),
    pl.col('trending_date').list.slice(-3, 1).alias('3rd_date_to_last'),
    pl.col('trending_date').list.slice(7).alias('from_8th_date_to_end')
).head()

In [ ]:
trending_dates_by_channel.select(
    'trending_date',
    pl.col('trending_date').list.gather([0, -1]).alias('first_and_last'),
    pl.col('trending_date').list.gather([0, 0, 0, 0]).alias('first_repeated'),
    pl.col('trending_date').list.gather([0, 10], null_on_oob=True).alias('first_and_10th_or_null'),
).head()

### There is more...

In [ ]:
(
    df
    .group_by('trending_date')
    .agg('category_id')
    .with_columns(pl.col('category_id').list.sort())
    .with_columns(
        pl.col('category_id'),
        pl.col('category_id').list.len().alias('category_id_cnt'),
        pl.col('category_id').list.unique().alias('category_id_unique'),
        pl.col('category_id').list.unique().list.len().alias('category_id_unique_cnt')
    )
).head()

In [ ]:
trending_dates_by_channel.with_columns(
    pl.col("trending_date")
    .list.sample(n=3, with_replacement=True, seed=0)
    .alias("samples")
).head()

## Applying logic to each element in lists

### Getting ready

In [ ]:
agg_df = (
    df
    .group_by('trending_date')
    .agg('views', 'channel_title')
)

In [ ]:
agg_df.head()

### How to do it...

In [ ]:
(
    agg_df
    .select(
        'views',
        pl.col('views').list.eval(pl.element()).alias('pl.element'),
        pl.col('views').list.eval(pl.element().first()).alias('pl.first'),
        pl.col('views').list.eval(pl.element().last()).alias('pl.last'),
        pl.col('views').list.eval(pl.element()).alias('pl.col')
    )
).head()

In [ ]:
channel_titles_df = (
    agg_df
    .select(
        pl.col("channel_title").list.head(2),
        pl.col("channel_title")
        .list.eval(pl.element().str.to_uppercase())
        .list.head(2)
        .alias("channel_title_upper")
    )
)
channel_titles_df.head()

In [ ]:
(
    channel_titles_df
    .with_columns(
        pl.col('channel_title_upper')
        .list.eval(
            pl.element().filter(
                pl.element().str.contains('A', literal=True)
            )
        )
    )
).head()

In [ ]:
(
    agg_df
    .select(
        'trending_date',
        'views',
        pl.col('views')
        .list.eval(pl.element().rank('dense', descending=True))
        .alias('views_rank'),
    )
).head()

In [ ]:
views_rank_df = (
    agg_df
    .select(
        'trending_date',
        'views',
        pl.col('views')
        .list.eval(pl.element().rank('dense', descending=True))
        .alias('views_rank'),
    )
)
views_rank_df.head()

In [ ]:
top3_views_df = (
    views_rank_df
    .explode('views', 'views_rank')
    .filter(pl.col('views_rank')<=3)
    .group_by('trending_date')
    .agg(pl.all())
)
top3_views_df.head()

In [ ]:
(
    views_rank_df
    .explode('views', 'views_rank')
).head()

In [ ]:
(
    top3_views_df
    .select(
        'views_rank',
        'views',
        pl.col('views')
        .list.eval(pl.element().max() - pl.element())
        .alias('diff from the most views')
    )
).head()

### There is more...

In [ ]:
top3_views_df.head()

In [ ]:
(
    top3_views_df
    .with_columns(
        pl.col('views_rank').list.slice(0, 2).alias('views_rank_1'),
        pl.col('views_rank').list.slice(-2, 2).alias('views_rank_2')
    )
    .select(
        'views_rank_1',
        'views_rank_2',
        pl.col('views_rank_1').list.set_intersection('views_rank_2')
        .alias('intersection'),
        pl.col('views_rank_1').list.set_union('views_rank_2')
        .alias('union'),
        pl.col('views_rank_1').list.set_difference('views_rank_2')
        .alias('difference'),
        pl.col('views_rank_1').list.set_symmetric_difference('views_rank_2')
        .alias('symmetric_difference'),
    )
).head()

## Working with structs and JSON data

### Getting ready

In [ ]:
import polars as pl

In [20]:
df = pl.read_json('../data/ga_20170801.json', infer_schema_length=1_000)
df.head()

shape: (5, 16)
┌───────────┬────────────┬────────────┬────────────┬───┬────────┬──────────┬───────────┬───────────┐
│ visitorId ┆ visitNumbe ┆ visitId    ┆ visitStart ┆ … ┆ userId ┆ clientId ┆ channelGr ┆ socialEng │
│ ---       ┆ r          ┆ ---        ┆ Time       ┆   ┆ ---    ┆ ---      ┆ ouping    ┆ agementTy │
│ null      ┆ ---        ┆ str        ┆ ---        ┆   ┆ null   ┆ null     ┆ ---       ┆ pe        │
│           ┆ str        ┆            ┆ str        ┆   ┆        ┆          ┆ str       ┆ ---       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ str       │
╞═══════════╪════════════╪════════════╪════════════╪═══╪════════╪══════════╪═══════════╪═══════════╡
│ null      ┆ 1          ┆ 1501591568 ┆ 1501591568 ┆ … ┆ null   ┆ null     ┆ Organic   ┆ Not       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆ Search    ┆ Socially  │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Engaged   │
│ null      ┆ 2          ┆ 1501589647 ┆ 1501589647 ┆ … ┆ null   ┆ null     ┆ Referral  ┆ Not       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Socially  │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Engaged   │
│ null      ┆ 1          ┆ 1501616621 ┆ 1501616621 ┆ … ┆ null   ┆ null     ┆ Referral  ┆ Not       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Socially  │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Engaged   │
│ null      ┆ 1          ┆ 1501601200 ┆ 1501601200 ┆ … ┆ null   ┆ null     ┆ Referral  ┆ Not       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Socially  │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Engaged   │
│ null      ┆ 1          ┆ 1501615525 ┆ 1501615525 ┆ … ┆ null   ┆ null     ┆ Referral  ┆ Not       │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Socially  │
│           ┆            ┆            ┆            ┆   ┆        ┆          ┆           ┆ Engaged   │
└───────────┴────────────┴────────────┴────────────┴───┴────────┴──────────┴───────────┴───────────┘

In [21]:
cols = ['visitId', 'date', 'totals', 'trafficSource', 'customDimensions', 'channelGrouping']
df = df.select(cols)
df.head()

shape: (5, 6)
┌────────────┬──────────┬──────────────────┬──────────────────┬──────────────────┬─────────────────┐
│ visitId    ┆ date     ┆ totals           ┆ trafficSource    ┆ customDimensions ┆ channelGrouping │
│ ---        ┆ ---      ┆ ---              ┆ ---              ┆ ---              ┆ ---             │
│ str        ┆ str      ┆ struct[13]       ┆ struct[9]        ┆ list[struct[2]]  ┆ str             │
╞════════════╪══════════╪══════════════════╪══════════════════╪══════════════════╪═════════════════╡
│ 1501591568 ┆ 20170801 ┆ {"1","1","1",nul ┆ {null,"(not set) ┆ []               ┆ Organic Search  │
│            ┆          ┆ l,"1",null,nul…  ┆ ","(direct)","…  ┆                  ┆                 │
│ 1501589647 ┆ 20170801 ┆ {"1","1","1",nul ┆ {"/analytics/web ┆ [{"4","APAC"}]   ┆ Referral        │
│            ┆          ┆ l,"1",null,nul…  ┆ /","(not set)"…  ┆                  ┆                 │
│ 1501616621 ┆ 20170801 ┆ {"1","1","1",nul ┆ {"/analytics/web ┆ [{"4","EMEA"}]   ┆ Referral        │
│            ┆          ┆ l,"1",null,nul…  ┆ /","(not set)"…  ┆                  ┆                 │
│ 1501601200 ┆ 20170801 ┆ {"1","1","1",nul ┆ {"/analytics/web ┆ [{"4","North     ┆ Referral        │
│            ┆          ┆ l,"1",null,nul…  ┆ /","(not set)"…  ┆ America"}]       ┆                 │
│ 1501615525 ┆ 20170801 ┆ {"1","1","1",nul ┆ {"/analytics/web ┆ [{"4","North     ┆ Referral        │
│            ┆          ┆ l,"1",null,nul…  ┆ /","(not set)"…  ┆ America"}]       ┆                 │
└────────────┴──────────┴──────────────────┴──────────────────┴──────────────────┴─────────────────┘

In [22]:
df.select('totals', 'trafficSource', 'customDimensions').head()

shape: (5, 3)
┌─────────────────────────────────┬─────────────────────────────────┬─────────────────────────┐
│ totals                          ┆ trafficSource                   ┆ customDimensions        │
│ ---                             ┆ ---                             ┆ ---                     │
│ struct[13]                      ┆ struct[9]                       ┆ list[struct[2]]         │
╞═════════════════════════════════╪═════════════════════════════════╪═════════════════════════╡
│ {"1","1","1",null,"1",null,nul… ┆ {null,"(not set)","(direct)","… ┆ []                      │
│ {"1","1","1",null,"1",null,nul… ┆ {"/analytics/web/","(not set)"… ┆ [{"4","APAC"}]          │
│ {"1","1","1",null,"1",null,nul… ┆ {"/analytics/web/","(not set)"… ┆ [{"4","EMEA"}]          │
│ {"1","1","1",null,"1",null,nul… ┆ {"/analytics/web/","(not set)"… ┆ [{"4","North America"}] │
│ {"1","1","1",null,"1",null,nul… ┆ {"/analytics/web/","(not set)"… ┆ [{"4","North America"}] │
└─────────────────────────────────┴─────────────────────────────────┴─────────────────────────┘

### How to do it...

In [23]:
df = df.with_columns(
    pl.struct('visitId', 'date', 'channelGrouping').alias('structFromCols')
)

In [24]:
(
    df
    .select(
        'visitId',
        'date',
        'channelGrouping',
        pl.struct('visitId', 'date', 'channelGrouping').alias('structFromCols')
    )
).head()

shape: (5, 4)
┌────────────┬──────────┬─────────────────┬─────────────────────────────────┐
│ visitId    ┆ date     ┆ channelGrouping ┆ structFromCols                  │
│ ---        ┆ ---      ┆ ---             ┆ ---                             │
│ str        ┆ str      ┆ str             ┆ struct[3]                       │
╞════════════╪══════════╪═════════════════╪═════════════════════════════════╡
│ 1501591568 ┆ 20170801 ┆ Organic Search  ┆ {"1501591568","20170801","Orga… │
│ 1501589647 ┆ 20170801 ┆ Referral        ┆ {"1501589647","20170801","Refe… │
│ 1501616621 ┆ 20170801 ┆ Referral        ┆ {"1501616621","20170801","Refe… │
│ 1501601200 ┆ 20170801 ┆ Referral        ┆ {"1501601200","20170801","Refe… │
│ 1501615525 ┆ 20170801 ┆ Referral        ┆ {"1501615525","20170801","Refe… │
└────────────┴──────────┴─────────────────┴─────────────────────────────────┘

In [26]:
(
    df
    .group_by('channelGrouping')
    .agg(
        'visitId', 
        pl.col('visitId').len().alias('numVisits')
    )
    .sort('numVisits')
    .with_columns(
        pl.col('visitId').list.to_struct(['visit_1', 'visit_2']).alias('struct_from_list')
    )   
)

shape: (7, 4)
┌─────────────────┬─────────────────────────────────┬───────────┬─────────────────────────────┐
│ channelGrouping ┆ visitId                         ┆ numVisits ┆ struct_from_list            │
│ ---             ┆ ---                             ┆ ---       ┆ ---                         │
│ str             ┆ list[str]                       ┆ u32       ┆ struct[2]                   │
╞═════════════════╪═════════════════════════════════╪═══════════╪═════════════════════════════╡
│ Display         ┆ ["1501651856", "1501625928", …… ┆ 12        ┆ {"1501651856","1501625928"} │
│ Paid Search     ┆ ["1501610896", "1501644116", …… ┆ 20        ┆ {"1501610896","1501644116"} │
│ Affiliates      ┆ ["1501604627", "1501572101", …… ┆ 29        ┆ {"1501604627","1501572101"} │
│ Referral        ┆ ["1501589647", "1501616621", …… ┆ 106       ┆ {"1501589647","1501616621"} │
│ Social          ┆ ["1501590147", "1501655923", …… ┆ 136       ┆ {"1501590147","1501655923"} │
│ Direct          ┆ ["1501586309", "1501587435", …… ┆ 163       ┆ {"1501586309","1501587435"} │
│ Organic Search  ┆ ["1501591568", "1501583103", …… ┆ 534       ┆ {"1501591568","1501583103"} │
└─────────────────┴─────────────────────────────────┴───────────┴─────────────────────────────┘

In [ ]:
(
    df
    .select(
        'structFromCols',
        pl.col('structFromCols').alias('structFromColsToBeUnpacked')
    )
    .unnest('structFromColsToBeUnpacked')
).head()

shape: (5, 4)
┌─────────────────────────────────┬────────────┬──────────┬─────────────────┐
│ structFromCols                  ┆ visitId    ┆ date     ┆ channelGrouping │
│ ---                             ┆ ---        ┆ ---      ┆ ---             │
│ struct[3]                       ┆ str        ┆ str      ┆ str             │
╞═════════════════════════════════╪════════════╪══════════╪═════════════════╡
│ {"1501591568","20170801","Orga… ┆ 1501591568 ┆ 20170801 ┆ Organic Search  │
│ {"1501589647","20170801","Refe… ┆ 1501589647 ┆ 20170801 ┆ Referral        │
│ {"1501616621","20170801","Refe… ┆ 1501616621 ┆ 20170801 ┆ Referral        │
│ {"1501601200","20170801","Refe… ┆ 1501601200 ┆ 20170801 ┆ Referral        │
│ {"1501615525","20170801","Refe… ┆ 1501615525 ┆ 20170801 ┆ Referral        │
└─────────────────────────────────┴────────────┴──────────┴─────────────────┘

In [28]:
(
    df
    .select(
        pl.col('trafficSource')
    )
    .unnest('trafficSource')
).head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ referralP ┆ campaign  ┆ source    ┆ medium   ┆ … ┆ adContent ┆ adwordsCl ┆ isTrueDir ┆ campaignC │
│ ath       ┆ ---       ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ickInfo   ┆ ect       ┆ ode       │
│ ---       ┆ str       ┆ str       ┆ str      ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│ str       ┆           ┆           ┆          ┆   ┆           ┆ struct[12 ┆ str       ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆ ]         ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null      ┆ (not set) ┆ (direct)  ┆ (none)   ┆ … ┆ null      ┆ {null,nul ┆ null      ┆ null      │
│           ┆           ┆           ┆          ┆   ┆           ┆ l,null,nu ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ll,null,n ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ull…      ┆           ┆           │
│ /analytic ┆ (not set) ┆ analytics ┆ referral ┆ … ┆ null      ┆ {null,nul ┆ null      ┆ null      │
│ s/web/    ┆           ┆ .google.c ┆          ┆   ┆           ┆ l,null,nu ┆           ┆           │
│           ┆           ┆ om        ┆          ┆   ┆           ┆ ll,null,n ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ull…      ┆           ┆           │
│ /analytic ┆ (not set) ┆ analytics ┆ referral ┆ … ┆ null      ┆ {null,nul ┆ null      ┆ null      │
│ s/web/    ┆           ┆ .google.c ┆          ┆   ┆           ┆ l,null,nu ┆           ┆           │
│           ┆           ┆ om        ┆          ┆   ┆           ┆ ll,null,n ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ull…      ┆           ┆           │
│ /analytic ┆ (not set) ┆ analytics ┆ referral ┆ … ┆ null      ┆ {null,nul ┆ null      ┆ null      │
│ s/web/    ┆           ┆ .google.c ┆          ┆   ┆           ┆ l,null,nu ┆           ┆           │
│           ┆           ┆ om        ┆          ┆   ┆           ┆ ll,null,n ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ull…      ┆           ┆           │
│ /analytic ┆ (not set) ┆ adwords.g ┆ referral ┆ … ┆ null      ┆ {null,nul ┆ null      ┆ null      │
│ s/web/    ┆           ┆ oogle.com ┆          ┆   ┆           ┆ l,null,nu ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ll,null,n ┆           ┆           │
│           ┆           ┆           ┆          ┆   ┆           ┆ ull…      ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [29]:
(
    df
    .select(
        'structFromCols',
        pl.col('structFromCols').struct.rename_fields(['a', 'b', 'c']).alias('renamedStructToBeUnpacked')
    )
    .unnest('renamedStructToBeUnpacked')
).head()

shape: (5, 4)
┌─────────────────────────────────┬────────────┬──────────┬────────────────┐
│ structFromCols                  ┆ a          ┆ b        ┆ c              │
│ ---                             ┆ ---        ┆ ---      ┆ ---            │
│ struct[3]                       ┆ str        ┆ str      ┆ str            │
╞═════════════════════════════════╪════════════╪══════════╪════════════════╡
│ {"1501591568","20170801","Orga… ┆ 1501591568 ┆ 20170801 ┆ Organic Search │
│ {"1501589647","20170801","Refe… ┆ 1501589647 ┆ 20170801 ┆ Referral       │
│ {"1501616621","20170801","Refe… ┆ 1501616621 ┆ 20170801 ┆ Referral       │
│ {"1501601200","20170801","Refe… ┆ 1501601200 ┆ 20170801 ┆ Referral       │
│ {"1501615525","20170801","Refe… ┆ 1501615525 ┆ 20170801 ┆ Referral       │
└─────────────────────────────────┴────────────┴──────────┴────────────────┘

In [30]:
(
    df
    .select(
        'structFromCols',
        pl.col('structFromCols').struct.field('channelGrouping')
    )
).head()

shape: (5, 2)
┌─────────────────────────────────┬─────────────────┐
│ structFromCols                  ┆ channelGrouping │
│ ---                             ┆ ---             │
│ struct[3]                       ┆ str             │
╞═════════════════════════════════╪═════════════════╡
│ {"1501591568","20170801","Orga… ┆ Organic Search  │
│ {"1501589647","20170801","Refe… ┆ Referral        │
│ {"1501616621","20170801","Refe… ┆ Referral        │
│ {"1501601200","20170801","Refe… ┆ Referral        │
│ {"1501615525","20170801","Refe… ┆ Referral        │
└─────────────────────────────────┴─────────────────┘

In [31]:
(
    df
    .select(
        pl.struct(
            pl.col('channelGrouping'),
            pl.col('trafficSource').struct.field('source')
        )
        .unique()
        .alias('channelAndSource')
    )
    .unnest('channelAndSource')
    .sort('channelGrouping', 'source')
)

shape: (28, 2)
┌─────────────────┬───────────────────┐
│ channelGrouping ┆ source            │
│ ---             ┆ ---               │
│ str             ┆ str               │
╞═════════════════╪═══════════════════╡
│ Affiliates      ┆ Partners          │
│ Direct          ┆ (direct)          │
│ Display         ┆ (direct)          │
│ Display         ┆ dfa               │
│ Organic Search  ┆ (direct)          │
│ …               ┆ …                 │
│ Social          ┆ groups.google.com │
│ Social          ┆ l.facebook.com    │
│ Social          ┆ m.facebook.com    │
│ Social          ┆ quora.com         │
│ Social          ┆ youtube.com       │
└─────────────────┴───────────────────┘

### There is more...

In [42]:
total_struct_to_str_expr = pl.col('totals').struct.json_encode()
(
    df
    .select(
        total_struct_to_str_expr.alias('total_str'),
        total_struct_to_str_expr
        .str.json_decode(dtype=pl.Struct({
            'visits': pl.String,
            'hits': pl.String,
            'pageviews': pl.String,
            'bounces': pl.String,
        }))
        .alias('total_struct')
    )
).head()

shape: (5, 2)
┌─────────────────────────────────┬───────────────────┐
│ total_str                       ┆ total_struct      │
│ ---                             ┆ ---               │
│ str                             ┆ struct[4]         │
╞═════════════════════════════════╪═══════════════════╡
│ {"visits":"1","hits":"1","page… ┆ {"1","1","1","1"} │
│ {"visits":"1","hits":"1","page… ┆ {"1","1","1","1"} │
│ {"visits":"1","hits":"1","page… ┆ {"1","1","1","1"} │
│ {"visits":"1","hits":"1","page… ┆ {"1","1","1","1"} │
│ {"visits":"1","hits":"1","page… ┆ {"1","1","1","1"} │
└─────────────────────────────────┴───────────────────┘

In [44]:
df.select(total_struct_to_str_expr.alias('total_str')).item(0,0)

'{"visits":"1","hits":"1","pageviews":"1","timeOnSite":null,"bounces":"1","transactions":null,"transactionRevenue":null,"newVisits":"1","screenviews":null,"uniqueScreenviews":null,"timeOnScreen":null,"totalTransactionRevenue":null,"sessionQualityDim":"1"}'